### ISSUE TITLE
FTP commands isn't work with NetKit ftp client

### ISSUE THREAD

**Issue by Nyoroon** [roxas75/rxTools#107]
FTP commands in [rxtools/Makefile](https://github.com/roxas75/rxTools/blob/master/rxtools/Makefile) isn't work with [NetKit](http://www.hcs.harvard.edu/~dholland/computers/netkit.html) ftp client:
```
$ make
Name (mirrorcatalogs.com:nyoroon): Please login with USER and PASS.
SSL not available
Password:
convert: unable to open image `unifont-8.0.01.bmp': No such file or directory @ error/blob.c/OpenBlob/2701.
convert: no images defined `gray:font.tmp' @ error/convert.c/ConvertImageCommand/3210.
Makefile:124: recipe for target 'font.bin' failed
make: *** [font.bin] Error 1
```

**Comment by Nyoroon** [comment]
So why not wget?

**Comment by dukesrg** [comment]
@Nyoroon there is no get in devkitPRO/msys package. I'd gladly use curl/wget but we have a lot of windows devs which will be much more unhappy about not working font download than more experienced linux -based. But you're right, as soon as I added different download method for Windows/devkitPRO, we can use wget here for normal download!

**Comment by soarqin** [comment]
We can write a python script to fetch it

**Comment by dukesrg** [comment]
@soarqin I'll fix it with wget for linux builds.

**Comment by 173210** [comment]
@dukesrg We can just include the file.
