### ISSUE TITLE
New building system

### ISSUE THREAD

**Issue by roxas75** [roxas75/rxTools#11]
Actually i need someone to change the building setup in a makefile-based one.
This will improve stability, make it easier to understand and portable to other platforms.

**Comment by Syphurith** [comment]
If possible the `.gitignore` should be updated to omit some intermidate files of builds. Also if something such as `rxTools.dat` is changed per commit, i don't suggest to include it in the main repo.

**Comment by roxas75** [comment]
I was keeping it just becouse people can download all the latest builds.

**Comment by Syphurith** [comment]
@roxas75 This would increase git repo size, as it does not diff binaries. Well al okey then.

**Comment by roxas75** [comment]
I am a bit new to github. Is it a big problem?

**Comment by dukesrg** [comment]
You can just add the latest build as a draft release

**Comment by Syphurith** [comment]
@roxas75 Not really a big problem, but for those who have a poor network..
Also `.git` folder would have a size increase (around 4MB as rxtools.dat is) each time that is commited.
This folder is hidden in the repo. Really all okey then if don't care about these problems.

**Comment by roxas75** [comment]
Then i'll probably decide to delete it if someone will encounter these kind of problems :)

**Comment by roxas75** [comment]
I can close this.
While it can be improved, we actually have a working building system. It took me an hour.

**Comment by dukesrg** [comment]
I believe you'd better add the latest build binaries as a draft relese - went ready to download and check the latest hijhax and .dat - and nothing available :(
