### ISSUE TITLE
GBA virtual console  black screen on my 4.5JP console with original gba_firm in rxmode sysnand/emunand.

### ISSUE THREAD

**Issue by wangyu-** [roxas75/rxTools#111]
Happens on rxtools 2.6/3.02b. Not test on 2.5.2. 
Emunand is 4.5 and 9.8,both tested. 
My emunand is linked,I think linked/unlinked is same in this case.

After replace gba_firm in sysnand with a already patched one with crc32 5609403D  and let rxtools recreate 0004013800000202.bin ,problem solved in both sysnand and emunand 

I have found a solution for myself. Maybe it is a bug.Or we should write which version of gba_firm is support in document.
More detail in:
https://gbatemp.net/threads/a-solution-for-gba-virtual-console-blackscreen-in-rxtool2-6-3-0b2-maybe-a-bug.394183/

**Comment by motezazer** [comment]
Fixed with latest commits.
