### ISSUE TITLE
Remove themes' dependence on language

### ISSUE THREAD

**Issue by 173210** [roxas75/rxTools#112]
Currently themes depend on languages. It causing the following issues.

* It's difficult to create a new theme.
* It's difficult to add a new feature.
* Many languages won't be supported (the theme included in this repository only supports English) .

Language-dependent theme looks very nice, but it has problems which can't be ignored.

Here is my idea of the language-independent theme implementation

* Remove most characters in theme

* Use JSON configuration to define the place to draw characters.

```JS
{
	"STR_FUNCTION_BAR": {
		"Display": "Bottom",
		"X": 16,
		"Y": 300
	}
}
```

**Comment by soarqin** [comment]
so do we need an individual font for each theme use?

**Comment by 173210** [comment]
@soarqin It's not always necessary. It depends.

**Comment by dukesrg** [comment]
@173210 we should hold it for a while. I'm transferring all strings into translation now, revising and unifying it. Many strings are reused, so it won't be just as easy as specifying place for a string.

**Comment by lavanoid** [comment]
Wouldn't a better solution be to make a "theme creation tool" that makes it easier to made/translate the themes themselves? I was using Game Maker, to help out with theme creation. I could completely make a theme with code then run and screenshot it. The screenshots can be used as the theme files.

Then all the theme dev would need to do is import the translated strings, make a few tweaks and export it as a theme.

**Comment by dukesrg** [comment]
@173210 I'm just extracting all string data from code into json and optimizing clauses at the same time . It myst be done anyway. After that themes redesign may be done.
