### ISSUE TITLE
Spider entry point has died.

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#116]
I built the latest commit of rxTools and the Spider entry point seems to have broken. I've tried it myself and someone else has also experienced this issue.

Can you compile it youself and confirm that this problem is legit? Not sure if I have a "bad compile" (which I doubt) but would be great to have confirmation.

**Comment by 173210** [comment]
The latest one works with http://lanunch.rxtools.net/. Did you host the page yourself?

**Comment by lavanoid** [comment]
Nope. I used the rxTools.net, the same link that you provided. I'm using sysver 9.2.0-20E btw.

I'll recompile later and give my results.

**Comment by 173210** [comment]
I'm on 4.5.0-10J. But I don't think it makes difference.

**Comment by lavanoid** [comment]
Hmm. Weird. Could you give me a copy of your build so I can test?

**Comment by 173210** [comment]
Sure.
https://github.com/173210/rxTools/releases/tag/d0

**Comment by lavanoid** [comment]
Okay, that's weird... Your build works but my one doesn't... I'm definitely using the latest commits...

**Comment by 173210** [comment]
Which version of GCC are you using?
```shell-session
root3@root3-X230t:~/CTR/rxTools$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (devkitARM release 44) 4.9.2
```

**Comment by lavanoid** [comment]
Same as yours, by the looks of it.

C:\Users\Lavanoid>arm-none-eabi-gcc --version
arm-none-eabi-gcc (devkitARM release 44) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is my path variable (just in case you need it):

C:\Program Files\ImageMagick-6.9.1-Q16;c:\devkitPro\msys\bin;C:\devkitPro\devkitARM\bin;C:\MinGW\bin;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Overlook Fing 2.2\bin;C:\Users\Lavanoid\bin;

**Comment by 173210** [comment]
Hello Windows :P
Others who use Windows may have the same problem (my intuition says so) .

**Comment by dukesrg** [comment]
Too bad, because it's not only windows bust most likely devkitpro

**Comment by lavanoid** [comment]
Haha :3 Maybe.

I'm recloning the repo now. Gonna **attempt** a rebuild and see how it goes. It used to compile without issues until I had to reinstall Windows, the other day (Windows 10 - buggy as hell).

**Comment by dukesrg** [comment]
Win10 - thats gonna hurt %)
Can only build now on Win7 - but can't check.

**Comment by lavanoid** [comment]
I'm running Windows 8.1 (Don't judge. I like it, okay?). rxTools used to build without any issues, then I made the mistake of upgrading to Win 10 and discovered how messed up it was. Had to do a clean install of 8.1 :/  Just rebuilt and still a no-go.

I'll see if any faffing around will fix anything.

**Comment by 173210** [comment]
@lavanoid Yes, Windows 8.1 is good. My Windows 10 is half-broken (maybe because of the preview builds).

**Comment by lavanoid** [comment]
@173210 If the preview build of w10 is really that bad, I shoud've expected the public release to be rubbish, haha :P 

The issue I have with W10 are the EULA (Microsoft basically state they have access to all your stuff), Cortana (She's a nosy b***h, reads your emails and everything then sends it off to Microsoft), Lack of flexibility over Windows Updates, Bluetooth Driver sucks, Start Menu doesn't always work, Windows Updates breaks sometimes (can't install), lack of theme options (compared to W8). Eh. 

Too much. 

Just did something with my PATH variable. Checking now :)

**Comment by lavanoid** [comment]
Nope. Still not working :/

**Comment by lavanoid** [comment]
Just some info that **may** help with debugging this. When I launch it via CN *then* through Spider then through CN again, it shows an error message on the bottom screen about unable to load a language file. I dunno if that has any relation to the error...

**Comment by dukesrg** [comment]
@lavanoid 
get rxtools.dat from @173210 build and just fc /b both files. At least we will have offsets and may  guess what compiled wrong.

**Comment by lavanoid** [comment]
Okey doke. Will do.

**Comment by 173210** [comment]
@lavanoid Note that I built my own repository. Check out this.
https://github.com/173210/rxTools

**Comment by lavanoid** [comment]
@173210 Still gonna compare both the file you provided and my own build. Then I'll build your repo and test.

**Comment by lavanoid** [comment]
@dukesrg This is the file comparison: https://dl.dropbox.com/s/pglbwabt2jxeewq/filecompare.txt?dl=0

**Comment by 173210** [comment]
@lavanoid Ok, so it's completely different. LOL

**Comment by lavanoid** [comment]
@173210 Looks it :P  I'm gonna compile your repo now, hang on ;)

**Comment by lavanoid** [comment]
@173210 Your version doesn't even build :/

make[2]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/numbers_rxtools/
rxTools/rxmode/native_firm/source/payload'
arm-none-eabi-gcc -g -Wall arm9/myThread/myThread.c arm9/myThread/handlers.s -c
-mcpu=arm946e-s -march=armv5te -mlittle-endian -fshort-wchar -fno-zero-initializ
ed-in-bss -Os -Iinclude
arm-none-eabi-gcc -c arm11/hookswi.s
arm-none-eabi-gcc -g arm9/EmuNAND.s arm9/CreateThread.s arm9/myThread/FS.S -I ar
m9/myThread -c -mcpu=arm946e-s -march=armv5te -mlittle-endian -fshort-wchar
arm-none-eabi-gcc -nostdlib -T 3ds.ld EmuNAND.o CreateThread.o myThread.o handle
rs.o hookswi.o FS.o -o payload.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-e
abi/bin/ld.exe: warning: cannot find entry symbol _start; defaulting to 0801a4c0

rm -f *.o
make[2]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/numbers_rxtools/r
xTools/rxmode/native_firm/source/payload'
arm-none-eabi-as source/k9_fix_flags.s -o build/k9_fix_flags.o
arm-none-eabi-ld -s -R source/payload/payload.elf -Tscript.ld build/k9_fix_flags
.o -o build/k9_fix_flags.elf
arm-none-eabi-as source/p9_keyx_spoof.s -o build/p9_keyx_spoof.o
arm-none-eabi-ld -s -R source/payload/payload.elf -Tscript.ld build/p9_keyx_spoo
f.o -o build/p9_keyx_spoof.elf
build/p9_keyx_spoof.o:(.patch.p9.keyx+0x10): undefined reference to `KEYXSPACE'
make[1]: *** [build/p9_keyx_spoof.elf] Error 1
rm build/k9_fix_flags.o build/p9_keyx_spoof.o
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/numbers_rxtools/r
xTools/rxmode/native_firm'
make: *** [rxmode/native_firm/nat_patch.elf] Error 2

C:\Users\Lavanoid\Documents\GitHub\numbers_rxtools\rxTools>


Do you think you could do a completely clean build of rxTools from this repo? That way, I can compare my clean build and yours.

**Comment by 173210** [comment]
@lavanoid It should be fine now. By the way, it's strange that you have the error while I, using the same toolchain, don't.
c7be30c8c4dfa2007424500fde50dc0ddb82912a

**Comment by lavanoid** [comment]
Will check in a bit. Anyways, this is everything that my system built: https://dl.dropbox.com/s/ajvd3fsjh11pso5/rxToolsrelease016339533cb5.zip?dl=0

I'm gonna go sleep in a bit so I guess you guys can have fun with that, if you'd like :)

**Comment by lavanoid** [comment]
Just built the commit that you linked me to. Builds without any issues but Spider entry point still won't work :/

**Comment by dukesrg** [comment]
Should link #117 to hold with merge for a while

**Comment by lavanoid** [comment]
Okay now I have no idea at all. Just compiled this repo with Ubuntu and Spider still refuses to work :/

Have any of you tried compiling on a "clean install" system?

**Comment by dukesrg** [comment]
@lavanoid I suppose prevous working build for you was not 2.6+ with old CakeHax ?

**Comment by lavanoid** [comment]
The last working build for me was from a few weeks ago. Still used CakeHax (likely not the most recent version, however). Wish I still kept the files when I reinstalled Windows :/

All I know is that it was "newish" since it still had the new UI :)

Once I find the revision I was using, I'll be sure to let you know (I haven't slept in nearly 24 hours so sorry that I can't continue with this issue until later).

**Comment by lavanoid** [comment]
Do you think you could run a clean installation of Windows in a Virtual Machine so you could debug this? If you encounter the same issue, you may be able to figure out what's causing it.

**Comment by dukesrg** [comment]
@lavanoid if it was the old version, looks liek you're just launching it wrong way. try
http://dukesrg.no-ip.org/3ds/cakes?rxTools.dat
since CakeHax are not using GW encryption anymore. I didn't track rxtools.net is updated with new html payload.

**Comment by lavanoid** [comment]
@dukesrg You're amazing! Thank you! That was the problem all this time! :D Where can I get a copy of this payload? Would be handy for me to host on my own server :)

**Comment by dukesrg** [comment]
dukesrg.github.io, index.html is the one! Close issue pls

**Comment by lavanoid** [comment]
Okey doke. Thanks! :D

**Comment by 173210** [comment]
@dukesrg By the way, does any other entry point need updated?

**Comment by dukesrg** [comment]
@173210 GW encryption was turned off and entry points was moved about two weeks ago and CakeHax reference in rxtools was updated shortly. Then it stayed untouched, but since nobody added a note or created a release several users just was using an old version with GW entry until now :)
