### ISSUE TITLE
Latest source breaks SaveDataFiler...

### ISSUE THREAD

**Issue by ApacheThunder** [roxas75/rxTools#118]
Not sure what happened. Compiled the latest source and started emunand. SaveDataFiler is now reporting broken save data for games that should have working saves. (like Pokemon Alpha Sapphire for example). However I start those games up and their saves are working fine. Something changed since the last time I used rxtools as SaveDataFiler is now mostly broken in emunand. (I'm on 9.9 USA firmware)

EDIT: Nevermind maybe? Rebooted and now I see a valid save for my ORAS game. Perhaps I scrolled the list too far. There is a duplicate entry for both my pokemon games that show as broken. (with quite a few other unique ids showing broken saves)

Not sure if that's normal or not....

**Comment by 173210** [comment]
If you do no longer have the error, you may close this issue.

**Comment by ApacheThunder** [comment]
If it becomes a recurring problem, I'll reopen it. But for now I agree. I will close it for now. :P
