### ISSUE TITLE
Number of entries in translation json file is limited to 63

### ISSUE THREAD

**Issue by dukesrg** [roxas75/rxTools#119]
I'm unable to load translation file with over 63 entries. It's not buffer/string length issue, looks like jsmn fails to parse over, but actualy don't see any limitation in there.
I already extracted about a hundred literals for translation and this number is reduced comparing with the original strings number in rxTools, so it won't fit into that limit for sure.

**Comment by Syphurith** [comment]
I don't know if a simplier parser which just setting the values when reading files would suit this need.

**Comment by dukesrg** [comment]
So I've got a negative count returned from jsmn_parse.

**Comment by dukesrg** [comment]
Fixed in #131
