### ISSUE TITLE
Spider entry point appears broken in latest build...

### ISSUE THREAD

**Issue by ApacheThunder** [roxas75/rxTools#124]
It seems somewhere along the line spiderhax entry point was broken. Browser just keeps crashing now. MSET entry point still works though. Using the correct version of the browser for 9.2 sysnand on my USA o3DS. Cleared cookies and all that jazz. It still crashes.

**Comment by dukesrg** [comment]
Are you using the updated CakeHax launcher page or old GW method?

**Comment by ApacheThunder** [comment]
Hmm. Not sure. I'm using this:

http://www.battlefieldsingleplayer.com/apachethunder/Images/gateway/rxtools.htm

Which I believe was based on an older version of your load code site. If that's similar to the GW method then perhaps I'll need to change the URL. Do you have the html file? I will upload it to my server and edit my bookmark accordingly. :P

**Comment by ApacheThunder** [comment]
Can you link me to the updated CakeHax launcher? I can't find it... :P

**Comment by dukesrg** [comment]
@ApacheThunder gwr encryption is no more used and there is only on entry for spider now. Launcger page is 
http://dukesrg.no-ip.org/3ds/cakes?rxTools.dat
And
http://dukesrg.github.io?rxTools.dat
