### ISSUE TITLE
msetdg.py doesn't work now

### ISSUE THREAD

**Issue by Nyoroon** [roxas75/rxTools#130]
```
Select your 3DS region :

    [1] JPN (4.x MSET)
    [2] JPN (6.x MSET)

    [3] USA (4.x MSET)
    [4] USA (6.x MSET)

    [5] EUR (4.x MSET)
    [6] EUR (6.x MSET)

    [7] KOR (4.x MSET)
    [8] KOR (6.x MSET)

    [9] CHN (4.x MSET)

   [10] TWN (4.x MSET)

Selection : 2
Downloading MSET from the CDN...
HTTP Error: 404 http://nus.cdn.c.shop.nintendowifi.net/ccs/download/0004001000020000/00000022
```
That's for all options. Seems like Nintendo removed them.
msetdg.py is now useless.
These files can be hosted in tor or i2p if anyone have them.

**Comment by Syphurith** [comment]
@Nyoroon It is said that ninty has removed many legacy firmware update packages from its CDN.
So now the msetdg.py and 3dnus would be affected. You might have to search for those packages.

**Comment by Gadorach** [comment]
We've been working pretty hard to collect all the relevant firmware files over on GBATemp. We have most of the files you're looking for on 3DSISO. I'll see about rewriting msetdg.py to collect the correct files from other servers.

**Comment by lavanoid** [comment]
If you were to rewrite msetdg.py to download the files from somewhere else, wouldn't it sorta violate GBATemps rules thus meaning that the GitHub link for rxTools would have to be removed from the OP?

I remember making a script once that downloads firm0 and firm1, from my own server. I made a post on GBATemp but a moderator had to remove it as the files weren't hosted by Nintendo and were copyrighted.

**Comment by AlbertoSONIC** [comment]
I think somene should host a modded msetdg.py on an "iso" site... And we load it from the incoming Pc Companion App

**Comment by lavanoid** [comment]
Sounds like a plan :)

**Comment by nastys** [comment]
@AlbertoSONIC Have you started porting the PC app yet?

**Comment by AlbertoSONIC** [comment]
@nastys The ui is ready, I've yet to start to code ;)

**Comment by nastys** [comment]
@AlbertoSONIC Good :+1: 
Do I have to port it to Qt (for GNU/Linux and OS X) or is it cross-platform this time?

**Comment by AlbertoSONIC** [comment]
You'll have to port it :D

**Comment by nastys** [comment]
@AlbertoSONIC Alright, tell me the functionality to add to the program, so I can start right away. Send me a PM on GBAtemp if you want to keep something secret :wink:

**Comment by AlbertoSONIC** [comment]
I'll send you a pic of the gui this evening ;)

**Comment by motezazer** [comment]
Won't fix directly.
If someone want to host MSET DG files, he will, but it has no official support from the team (it's illegal).
