### ISSUE TITLE
Compilation errors on x86

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#135]
When I build the latest commits on Ubuntu 32 bit (x86), I get this: https://youtu.be/gOowvOVpqk8  but when I compiled on Windows (64 bit), there was nothing wrong :/

I dun know why it's soo mean to me :(

I launched via Spider.

**Comment by Syphurith** [comment]
From the video i guess that is a mis-aligned font binary so the text still gets line border while corrupted.
Note: You could check the checksums (MD5, CRC32) of both font.bin generated by imagemagick.
Otherwise that means our font related code isn't so portable..

**Comment by lavanoid** [comment]
Hm. Will check later and post my results :)

**Comment by dukesrg** [comment]
@lavanoid update font.bin

**Comment by lavanoid** [comment]
@dukesrg  I've quite literally erased everything on my SD card and simply put the new rxTools directory onto the root of it. Everything is as updated as it gets :/

**Comment by lavanoid** [comment]
Okay, so it is something to do with the font.bin

I downloaded the latest commits onto both my windows (64 bit) machine and Linux (32 bit) machine.

I built them both and tested. I replaced the dodgy font file with the one that was made on Windows and it seems to be normal. I don't know why this anomaly is occurring :/

Should I provide the dodgy font.bin, for analysis?

**Comment by lavanoid** [comment]
I'd also like to note, instead of making another error report. rxTools freezes while trying to dump ticket.db from sysNAND. I don't know if this error occurs for any of the other options :/

**Comment by 173210** [comment]
I have no problem although I use Ubuntu.
```shell-session
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Wily Werewolf (development branch)
Release:	15.10
Codename:	wily
```

**Comment by lavanoid** [comment]
Hm. Are you using 32 bit or 64?

lavanoid@lavanoid-Compaq-Mini-110c-1000:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty

**Comment by 173210** [comment]
64 bit.
```shell-session
$ uname -a
Linux root3-X230t 4.1.0-3-generic #3-Ubuntu SMP Tue Jul 28 12:25:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lavanoid** [comment]
Hm... Would it be possible for font.bin to be pre-compiled in the repo? Either that or we find a way to fix the compilation bug that seems to make the font go weird...

$ uname -a
Linux lavanoid-Compaq-Mini-110c-1000 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux

**Comment by 173210** [comment]
@lavanoid Any repository shouldn't include a compiled binary, but you can copy a binary compiled with Windows.
By the way, is Windows x86, or x64?

**Comment by lavanoid** [comment]
Ah, I see. My windows is x64. It's just my Linux machine that's x86.

I guess I should modify my "automatic build" script to replace font.bin after it's compiled, then upload it to my Dropbox.

**Comment by 173210** [comment]
@lavanoid By the way, you can change the title because the issue is on x86, not Ubuntu.

**Comment by lavanoid** [comment]
Okey doke :)

**Comment by lavanoid** [comment]
Should I close this issue or leave it open?

**Comment by nastys** [comment]
@lavanoid Has this issue actually been solved?

**Comment by lavanoid** [comment]
@nastys I wouldn't say it was resolved, just diagnosed :)

We seem to be OUL with compiling on x86, so...

**Comment by nastys** [comment]
@lavanoid Then I'll reopen it until it's properly solved :blush: 
You should edit the first message as well.

**Comment by dukesrg** [comment]
@lavanoid did you
make clean
make release
amd copy all release/rxTools into sdcard/rxTools?

**Comment by lavanoid** [comment]
@nastys  Done

@dukesrg Yeah, I did all that. The font just doesn't build correctly on the x86 system :/

**Comment by dukesrg** [comment]
@lavanoid in /rxTools of a project:
convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - bmp:font1.bmp

convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - bmp:font2.bmp

Check results

**Comment by lavanoid** [comment]
Will check later this evening :) I'm not at the computer atm.

**Comment by nastys** [comment]
@lavanoid I'm literally having the opposite problem...
rxTools only works when build from my x86 Xubuntu VM. The font is fine (although there's no text except "LANGUAGE" in Options, but that's perhaps unrelated).
If I build it from my real, Ubuntu amd64 machine, the browser crashes telling me that I should shut down the console.

Are you sure it's the x86 architecture that is causing your issue?

**Comment by dukesrg** [comment]
@nastys if only language is displayed then en.json or whatever was the last is not loaded. Clear settings

**Comment by nastys** [comment]
@dukesrg There's no such file in the entire repo...

**Comment by dukesrg** [comment]
@nastys 
/release/rxTools/lang/en.json

**Comment by nastys** [comment]
@dukesrg Oh, I know why... I always delete the release folder before compiling.
Putting files directly into the release folder is a bad idea. Instead, they should be put in another folder and then copied by the Makefile.

**Comment by dukesrg** [comment]
@nastys make claen must clean the t all before build.

**Comment by lavanoid** [comment]
I'm not entirely sure what the cause is  to be honest. All I know is that it doesn't compile correctly on my x86 Ubuntu system.

Everything else works fine, so it seems. It's just the font. I wish I could provide more info on the matter, heck I'd even give you SSH access to the system if you really must.

**Comment by lavanoid** [comment]
@nastys  @dukesrg  I always run the "make clean" command before compiling. Doesn't change a thing, the bug is still there.

**Comment by lavanoid** [comment]
(Bumped the close button, accidentally. Touchscreens - gah)

**Comment by nastys** [comment]
@lavanoid Are you sure ImageMagick is installed?
Try deleting the repo then clone it again and delete the release folder before running make.

**Comment by lavanoid** [comment]
Yes, ImageMagick is definitely installed.

I've tried all that. It's a no-go. I'll mess about with it later this evening and see if I can get it fixed. If I can't, I try to send back my results/findings:)

**Comment by nastys** [comment]
@lavanoid Please try again with the latest commit...

**Comment by lavanoid** [comment]
Will do. Give me an hour and I'll get back to ya ;)

**Comment by lavanoid** [comment]
Built the latest commits (and ran "make clean" before building) and the result is the same - dodgy font.

I ran the commands that @dukesrg told me to run and this is the output:

lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools$ cd rxtools/
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ ls
build  font.bin  Makefile  rxtools.bin  rxtools.elf  source  stub.ld  unifont-8.0.01.bmp
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - bmp:font1.bmp
convert.im6: no images defined `unifont-8.0.01.bmp' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-EVTH400f' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `-' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-os2U0LEj' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `bmp:font1.bmp' @ error/convert.c/ConvertImageCommand/3044.
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ 
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp | convert -crop 16x4096 -append - - | convert -negate -depth 1 - bmp:font2.bmp
convert.im6: no images defined `unifont-8.0.01.bmp' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-7OUVXiwt' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `-' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-BDFebDNp' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `bmp:font2.bmp' @ error/convert.c/ConvertImageCommand/3044.
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ 
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp | convert -crop 16x4096 -append - - | convert -roll +8+0 -negate -depth 1 - bmp:font3.bmp
convert.im6: no images defined `unifont-8.0.01.bmp' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-PVY4pCBm' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `-' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: no decode delegate for this image format `/tmp/magick-x7jSKDdl' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `bmp:font3.bmp' @ error/convert.c/ConvertImageCommand/3044.
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$

**Comment by nastys** [comment]
@lavanoid Could you try in a clean (32 bit) VM?
Just follow these instructions:
http://3dbrew.org/wiki/Setting_up_Development_Environment
then install ImageMagick, clone rxTools recursively and build it.
It worked for me...

**Comment by lavanoid** [comment]
Yeah, I can try. Should I install the VM onto my x86 Linux system or onto the Windows x64? I'm asking because the x86 machine is a tiny Intel Atom @1.6Ghz, 2GB RAM.

Not sure if I'd get things done as quickly but meh. I'm convinced that ImageMagick is busted in Ubuntu's x86 Repo.

**Comment by nastys** [comment]
@lavanoid It doesn't matter, as long as you run it in a VM. I used VirtualBox on Ubuntu 15.04 (64 bit).
ImageMagick is fine, since it worked for me...
Maybe it doesn't work for you because you're using Ubuntu 14.04 LTS?

**Comment by lavanoid** [comment]
Yeah, I'm thinking the same thing. I'll run 14.04 LTS in a Virtual Machine on my x64 system, and see how it goes. If it persists, I'll try a different Linux disto.

**Comment by lavanoid** [comment]
Just compiled in a VM and the results are the same. Gonna go ahead and try another distro and report back :)

**Comment by nastys** [comment]
@lavanoid Try Xubuntu 15.04, which worked for me :grin:

**Comment by lavanoid** [comment]
Downloading it now :)

**Comment by nastys** [comment]
:+1:

**Comment by Syphurith** [comment]
@lavanoid `no images defined unifont-8.0.01.bmp` so quite possible there is no bitmap downloaded..
Please check if there is such a bitmap file in *(repo root)*/rxTools. if not you could fetch it manually

**Comment by lavanoid** [comment]
@Syphurith lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools$ cd rxtools/
lavanoid@lavanoid-Compaq-Mini-110c-1000:~/Desktop/rxTools/rxtools$ ls
build font.bin Makefile rxtools.bin rxtools.elf source stub.ld unifont-8.0.01.bmp

It exists :/

**Comment by Syphurith** [comment]
@lavanoid Sorry. Found that in your log. Search for the convert.im6 issue, and found this [URL](http://www.imagemagick.org/discourse-server/viewtopic.php?t=23456).
Try seperate the single line batch to several commands to see if it could be proceeded step by step.

**Comment by lavanoid** [comment]
Thanks for looking that up :) I'm installing xubuntu at the moment so I'll check that out as soon as I've finished sorting xbuntu :)

**Comment by Syphurith** [comment]
@lavanoid well hope xubuntu could solve this easier.
I don't know if your imagemagick is out of date.. so some features we are using aren't supported well.
for me, yep that is windows..
```
Version: ImageMagick 6.9.1-2 Q16 x86_64 2015-05-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC HDRI Modules OpenMP
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf xml zlib
```
Just a `convert --version` would tell you about it..

**Comment by lavanoid** [comment]
Thank you :)

lavanoid@lavanoid-Compaq-Mini-110c-1000:~$ convert --version
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

**Comment by nastys** [comment]
My PC and VM
![versions](https://cloud.githubusercontent.com/assets/7950891/9156723/566261b8-3ee4-11e5-9b84-60117a150025.png)

**Comment by lavanoid** [comment]
Yup, my ImageMagick is outdated. Thanks guys! :D Hopefully XUbuntu will solve this issue,

Will report back when done.

**Comment by lavanoid** [comment]
Should remove the "64 bit" requirement from the README and put down the required version of ImageMagick (9.8.9 >)

**Comment by nastys** [comment]
@lavanoid This means it worked?

**Comment by Syphurith** [comment]
@lavanoid If the one included in the software repo (i mean those you get when `apt-get install`) is still outdated, try compile it from source (checked the official download page and only rpm offered as binary)

**Comment by lavanoid** [comment]
Considering that both of you have a newer version of ImageMagick, I think its safe to assume that that's the problem. Restarting the VM and setting up the environment, now. I'm certain that ImageMagick is the cause, never the less.

**Comment by nastys** [comment]
@Syphurith The version I'm using is from the repo (*ubuntu 15.04)... and it works.

**Comment by lavanoid** [comment]
@Syphurith Will do :)

**Comment by Syphurith** [comment]
@nastys ok. So that should work. @lavanoid hope your issue gets solved.

**Comment by lavanoid** [comment]
@Syphurith Thanks :)  If I get issues with compiling ImageMagick,I'll just extract the .deb files from /var/cache/apt/archives/ and copy them over to my linux box :)

**Comment by Syphurith** [comment]
@lavanoid package managers are not that easy to cheat. Those you get inside the apt archives are the corresponding deb files from the software repo targeting the OS version on which you ran the apt commands. Compiling would certianly always get the latest and all be suited. So if your OS is already out of date (says 8.x LTS ubuntu for now, as an example) the deb files could still be for older ones.
All right if you even can solve it in such a way..  Note: if your own newer setup already works i think you don't need to compile it then.. Except you want to search for tutorial and try it.

**Comment by nastys** [comment]
Or... just connect the VM to the Internet and run:
sudo apt-get update
sudo apt-get install imagemagick

**Comment by lavanoid** [comment]
@Syphurith Yeah, you're probably right. I suppose it would be better to compile the source but I'm gonna attempt to cheat anyways :P If I manage to break something, I'm gonna just install xUbuntu onto my Linux machine, instead :)

@nastys Yeah, I could do everything from a VM but eh. In fact, I could do everything from Windows if I wanted to but I'm awkward, haha.

**Comment by Syphurith** [comment]
@lavanoid well it may not break it if you used the deb files from the same OS. Just remain outdated.
I don't know which version you're currently on so i can't say much things about so.
You may try this [link](http://pkgs.org/download/imagemagick) out -- binary in deb for 12.04, 14.04, 15.04 offered.

**Comment by lavanoid** [comment]
The current version I have is the same as what's hosted on that page you linked me to (imagemagick_6.7.7.10-6ubuntu3_i386.deb).

I'll just update my OS, less hassle IMO. *Waves goodbye to Ubuntu 14.04* :)

**Comment by Syphurith** [comment]
@lavanoid then you should get 6.8 so much less likely to meet the issue then. Hope it solved yup

**Comment by lavanoid** [comment]
yup :)

Just built rxTools in xUbuntu and everything is perfect. So yeah, requires a newer version of ImageMagick :D No font issue or anything.

**Comment by lavanoid** [comment]
Problem solved. Gonna close this issue :)
