### ISSUE TITLE
Freezes while dumping ticket.db

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#140]
Latest build freezes while dumping ticket.db from sysNAND. Haven't tried the other options :/

**Comment by dukesrg** [comment]
Wait, looks like emuDUMP freezes with any file dump just on  the menu with no dump dialog. Most likely I messed something when translateing nandtools.c

**Comment by lavanoid** [comment]
Yeah, that's exactly what happens to me :/

**Comment by dukesrg** [comment]
@lavanoid this #142 must resolve the issue. BTW, injection was also affected, fixed it but checked only dumping. Though at worst in only hangs because no actually pathes alterd whithin translation.

**Comment by lavanoid** [comment]
Okey doke :)

**Comment by lavanoid** [comment]
Yup, dumping works for me too. Just tested. I'll close this issue and reopen if something comes up :)
