### ISSUE TITLE
Can we bring the emuNAND notifier back?

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#148]
Remember on the old rxTools where it had the little console that indicated if it had found emuNAND and the keyslot? Think we could have that back? I have more than 1 SD card and it can be confusing when I launch rxTools but not remember if it had an emuNAND or not 0~0

**Comment by AlbertoSONIC** [comment]
Well this kind of thing ruins the theme... If you open the nand dumper, if the emunand is detected, it asks you to choose between emunand dump and sysnand dump. You can use this to know if the emunand is there. ;)

**Comment by dukesrg** [comment]
This feature should be added if someone will handle theme redesign. IMO with JSON support it will be done sooner or later (i.e. theme in json with string placement, backroung image names for each menu and smaller images and so on)

**Comment by soarqin** [comment]
@dukesrg make the sense, put strings in theme really make it hard to add/remove features to main menu, we should have theme redesigned.

**Comment by nastys** [comment]
When you start rxMode, it asks you which NAND you want to use.
I think it shouldn't if you don't have an emuNAND, or it should give an error if the user tries to boot in emuNAND mode.

**Comment by AlbertoSONIC** [comment]
@nastys I asked crusard, the gui guy, to make a boot screen with emunand button deactivated, so that if the emunand is not present, the user sees the emunand button deactivated and understands that there's no emunand ;)

**Comment by nastys** [comment]
:+1:

**Comment by dukesrg** [comment]
@soarqin that's right, theme must refer to the string names existing in language/translation files.
i.e. Theme file should look like that:
{
	"title": "Theme	name",
	"image": "background image file name",
	"color": [ 16777216, 0],
	"Main": {
		"image": "background image file name",
		"Title": {
			"Text": "MAIN_MENU_TITLE",
			"XY": [12, 34]
			"color": [ 16777216, 0]
		},
		"Content":{
			"Text": "CONTENT_HEADER_TEXT_IF_ANY"
			"XY": [12, 34]
		}
	},
	"Settings": {
	...
}
}

**Comment by soarqin** [comment]
It is not easy to maintain for multi-level json, yaml or toml could be better if binary size is not a big deal.

**Comment by dukesrg** [comment]
@soarqin 
We already have JSON parser. You want to add another one?
There are tons of validators so there will be no issues with that.

**Comment by lavanoid** [comment]
@nastys The idea about not showing emuNAND as an option while booting, is a great idea :+1:

**Comment by soarqin** [comment]
@dukesrg 
Actually I don't think this is necessary, but a more friendly config format is a benefit to theme maintainers at least.
And I just gave a suggestion of change json to another parser, not keep both.
Also if using yaml, yaml is a superset of json, so change to yaml could keep current json files.

**Comment by motezazer** [comment]
Added with latest commits.

**Comment by lavanoid** [comment]
Yay
