### ISSUE TITLE
Installation data suite always initialises on O3DS

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#191]
Seems that the recent commits to rxTools has broken something. Deleted the rxTools directory and placed the newly created one that's in the "release" directory.

Just another lil bug report to add to the "to-do list" :)

**Comment by lavanoid** [comment]
I've also noticed that it doesn't save settings. When I launch it, it forgets the theme config and all that stuff :/

**Comment by dukesrg** [comment]
Each time even with not updating code.bin?

**Comment by lavanoid** [comment]
I haven't tried that an I doubt it matters. Eveything in my rxTools directory is from a fresh compile. Removed the one that was already on my SD card and replaced it with the new one.

I haven't tried an older code.bin

**Comment by dukesrg** [comment]
Updating code.bin forces rxTools to reinitialize. I meant gave you tried to boot two times in a row with untouched code.bin

**Comment by lavanoid** [comment]
I don't think it would make a difference. I booted two times in a row with the latest version of rxTools and each time, the data setup would initialise. It was the same code.bin as the first time I booted it.

**Comment by soarqin** [comment]
#194 fixed it

**Comment by lavanoid** [comment]
Now the installation always fails, on the latest commit.

**Comment by soarqin** [comment]
@lavanoid firmware.bin is moved into rxtools/system/

**Comment by lavanoid** [comment]
@soarqin Thanks! I didn't notice the commit that made that change :)
