### ISSUE TITLE
Build in Windows

### ISSUE THREAD

**Issue by dukesrg** [roxas75/rxTools#20]
Just sent a pool request with all the links with Windows specific info. Just two small notices
1. make from the latest devkitPRO crashes, but it may be substituted with GNUWIN32 Make from here http://gnuwin32.sourceforge.net/packages/make.htm
2. armips must be build from the sources, I've used VS2013 express, if this  is the only option for Windows, the reference must be added to the build section too.

**Comment by dukesrg** [comment]
Just created apoolrequest with updated requirements and links for build toolchain for Windows.
I will also try to port assembler code to devkit compiler, should not be a big deal. Thus we'll get rid of armips requirement along with VS

**Comment by roxas75** [comment]
Uh... I really liked the versatility of armips :(

**Comment by dukesrg** [comment]
As far as I can see now there is only .create directive that can't be easily ported to AS.

**Comment by roxas75** [comment]
I've choosen it since it was easy and fast on compiling, and i found it very useful in rxmode patches to manipulate the filename and the addresses.

**Comment by dukesrg** [comment]
I made a noarmips branch in my fork and try to do same triks with AS and LD. Anyway I have only a github web access until evening and not able to build anything :(

**Comment by roxas75** [comment]
Well, there is no hurry, if you come out with something good we'll adopt it :)

**Comment by dukesrg** [comment]
Well, being able to build&test I'd better work with C-code ;)

**Comment by dukesrg** [comment]
I'll keep rebasing noarmips branch with the latest master branch for a while.

**Comment by dukesrg** [comment]
I suppose now windows build is described fully, so closing the issue
