### ISSUE TITLE
[MSET] O3DS SYSNAND 4.3 EUR does not start rxTools

### ISSUE THREAD

**Issue by julianxhokaxhiu** [roxas75/rxTools#217]
Hi guys,

i'm trying to use the latest version builds of rxTools these whole week hoping that I may find a version that is actually booting on my O3DS with SysNand 4.3 but actually it does not.

The only version that seems to work is 2.6 through rxTools.dat.

Of course I followed instructions and I placed all the files in the correct place and I've updated the MSET NDS hack through a DS cart ( the same I'm using to install 2.6 ) and when I try to go to my NDS profile through settings I just got a crash, while with 2.6 I get rxTools booting fine.

Am I missing something?

Thanks in advance!

**Comment by Syphurith** [comment]
Oh. I'm still using 2.6 rxTools with that old encrypted (GW-Style) payload.
My SysNAND is JPN 4.1 and i can not get it loaded too. Orz. *And partially gets myself off the project*

**Comment by kot2002** [comment]
Have you tried cakesfw? Two cfws share the same payload launcher (CakeHax).
If the problem reside in the CakeHax, cakesfw would fail to load.

**Comment by Syphurith** [comment]
@kot2002 I haven't. If ever tested with some time and issue i would report to them.

**Comment by julianxhokaxhiu** [comment]
Actually I've found a post on GBATemp where someone linked the MSET installer complied freshly from sources ( http://gbatemp.net/threads/release-rxtools-roxas75-3ds-toolkit-fw-2-0-9-2.382782/page-510#post-5634997 ) and this works for me.

So I'm guessing that nightlies built by people are missing something that he knows and maybe is not documented? Would it be good to know what so we can replicate it and maybe create a Docker image just for a safe compiling :)

**Comment by kot2002** [comment]
So, you can close this issue now :)

**Comment by julianxhokaxhiu** [comment]
Well...I was hoping some kind of collaboration from you, like adding missing steps that anyone is delivering a broken NDS installer. Doing this will make also the build bullerproof...but anyway, thanks.

**Comment by soarqin** [comment]
I will test it tomorrow on my jpn and twn o3ds to see if mset installer compiled from latest codes works

**Comment by soarqin** [comment]
@julianxhokaxhiu I tested both rxinstaller.nds and rxinstaller.bin(ROPSpider) on my 2 consoles, and are all worked fine.
I do think there should be something wrong with the compiling process of your rxinstallers, probably submodules are not in-sync. I found that many ppl don't understand work mechanism of submodules and always forget to sync them after pull codes from main repo

**Comment by julianxhokaxhiu** [comment]
Think so, I'm gonna do a Dockerfile to build rxTools by myself :) Thank you very much!
