### ISSUE TITLE
Xorpad Output Location Change

### ISSUE THREAD

**Issue by fox8091** [roxas75/rxTools#219]
Maybe change the xorpad output location from the root of the SD card to /rxTools/xorpads ?

**Comment by Syphurith** [comment]
It is possible however i don't like thus much. Currently you have two ways to change the location.

* [Here](https://github.com/roxas75/rxTools/blob/master/rxtools/source/features/padgen.c#L158) we would use what `ncchinfo.bin` says to create the path. You could have noticed that `ncchinfo.bin` generated these days points all xorpads path to SD root. Not difficult if you understand C, just find tutorials for `sprintf` and change the string.
* [Here](https://github.com/roxas75/rxTools/blob/master/tools/scripts/ncchinfo_gen.py#L319) the python script that generates the `ncchinfo.bin` configure the path. Seem easier for you to change. However be aware of the **string length limit of `ncchinfo.bin` entries**.

And? you would have to try to create this path, once entered the feature.
