### ISSUE TITLE
Broken Ninjhax entry

### ISSUE THREAD

**Issue by kot2002** [roxas75/rxTools#238]
bf9f72c992fc22e0e71148899c5aaf60976a6e81 broke ninjhax entry.
@nastys Removing BOT_SCREEN2 from brahma looks like the culprit.

**Comment by AlbertoSONIC** [comment]
It's because the BOT_SCREEN is 0x080FFFD4, not 0x080FFFD0. I'm not at home so I can't fix this...

**Comment by AlbertoSONIC** [comment]
Ok It should be fixed. Does it work?

**Comment by kot2002** [comment]
It runs, but bottom screen shows nothing but black.

**Comment by AlbertoSONIC** [comment]
Latest build with latest 3dsx?

**Comment by kot2002** [comment]
Changing into *((unsigned int*)0x080FFFD4) = 0x200C4E00; resolved the problem

**Comment by AlbertoSONIC** [comment]
Yeah I knew that would have fixed it. I just wanted to be sure ;)
