### ISSUE TITLE
Themehax blank screen

### ISSUE THREAD

**Issue by mariohackandglitch** [roxas75/rxTools#253]
On an old 3ds 9.2.0 after loading rxtools with Themehax I get bothe screens to be black.

**Comment by kot2002** [comment]
Did you launch rxTools via homebrew launcher or directly from renamed boot.3dsx?

**Comment by mariohackandglitch** [comment]
Both, and both of them shows black screen.

**Comment by kot2002** [comment]
#252 will fix this issue
