### ISSUE TITLE
Better file structuring :/

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#254]
Sorta sucks how we can only dump 1 file from nand. E.g. You wanna dump a ticket.db from both emuNAND and sysNAND but you cant because it'll overwrite the one that already exists.

Can't we add a date and time of when a file was dumped as well as add in indicator that shows where it was dumped from? For example:

emuNAND: ticketdbE_06.24.2015_19.15.db
sysNAND: ticketdbS_06.24.2015_19.15.db

Or have directories such as:

sdcard:/rxTools/dumps/ticket.db/sysNAND/<console ID>/<date>_<time>/ticket.db
sdcard:/rxTools/dumps/ticket.db/emuNAND/<console ID>/<date>_<time>/ticket.db

Is it possible from ARM9, to get the date and time?

**Comment by hartmannaf** [comment]
If somebody adds this, we will need a file selection for injecting files.

**Comment by lavanoid** [comment]
@AlbertoSONIC added the file manager for selecting firm, correct? Couldn't that code be "re-used" to select what to inject? (I'd don't write in C so I can't add the feature Dx)

**Comment by hartmannaf** [comment]
Haven't looked into the code, but in theory it should be possible.

**Comment by Syphurith** [comment]
To mark those paths, there are several ways.
* Use `,` or other hard to see chars inside the filename. Yup. Just don't exceed the file name max length.
* Use a dump log and use just numbers. Let another program on PC handles this.
* Similar file path. "A/B" dumps to "/dumps/A/B", quite simple.

For the time mark, i doubt if it can access the time registers easily.
Just for the original problem you faced, you can make it just have emunand or sysnand marked, such as "title.db.emu", or "emu_title.db" to avoid the overwrite. Much easier if you'd like to take a look.

**Comment by lavanoid** [comment]
The last idea sounds like the best option, with "emu_title.db". Since time registers may not be easy to implement, could the files be numbered instead? You know, if "emu_title.db" exists, name it to "emu2_title.db", "emu3_title.db" etc.

**Comment by AlbertoSONIC** [comment]
@lavanoid Yeah the file explorer is written to be easily used to load other files ;)

**Comment by lavanoid** [comment]
:+1:
