### ISSUE TITLE
[Cosmetic] Typo in gfx on Advanced menu

### ISSUE THREAD

**Issue by justinkb** [roxas75/rxTools#260]
Says "UNISTALL FBI" instead of "UNI*N*STALL FBI"

**Comment by AlbertoSONIC** [comment]
True, I'll contact the gfx guy (crusard)

**Comment by AlbertoSONIC** [comment]
Fixed with last commit ;)

**Comment by justinkb** [comment]
That was (incredibly) fast. Love this project, keep up the great work!

**Comment by AlbertoSONIC** [comment]
:D
