### ISSUE TITLE
CETK key generation for firmwares

### ISSUE THREAD

**Issue by 173210** [roxas75/rxTools#265]
A patch for CakesForeveryWan to implement the feature on CakesFW
mid-kid/CakesForeveryWan@b6a79e03324b38745cd319da174873bb09c391c4

This is suggested at https://github.com/roxas75/rxTools/commit/f18f72a18aa2f7d2974bdf7d4138efe745858508#commitcomment-13889106.

I made commit in 23cd7cd39348f9bb81b521c83906adc4a57c5a49 pull request #264 to enable to add more files such as CETK.

**Comment by 173210** [comment]
Solved with commit 9711d25fa8b746de1a710aa02c82caaad5974ca6.

**Comment by urherenow** [comment]
Saw a reference to SYSTEM_PATH In there... Shouldn't that have been changed to SYS_PATH? Or am I just getting lost in the changes? (Really just looking to figure out where to place cetk and what to name it for both o3ds and n3ds...

**Comment by 173210** [comment]
@urherenow Now there is no reference to SYSTEM_PATH. By the way, the path for o3ds is `rxTools/firm/0004013820000002_cetk.bin`. The one for n3ds is `rxTools/firm/0004013820000002_cetk.bin`.

**Comment by urherenow** [comment]
Thanks for the cetk bit! I almost figured it out from the source, but wasn't quite sure if it used the whole titleID or just The high part... Anyway, the commit I was looking at looks like it was done before renaming SYSTEM_PATH. I'm all good now (except for the latest tree... What to do for n3ds firm...)
