### ISSUE TITLE
Broken data installation

### ISSUE THREAD

**Issue by kot2002** [roxas75/rxTools#270]
OLD 3DS, 9.0.0-20E
I downloaded firm files with cdn_firm.py and put them in /rxTools/firm .
Data installation stops at the first progress bar.

**Comment by b-** [comment]
Same problem here, 9.2.0-20U. I tried launching via MSET, ThemeHax, and Spider.

**Comment by urherenow** [comment]
The read me doesn't say to put it there. Firmware.bin goes in rxtools/sys on o3ds. Rxtools/data on n3ds

**Comment by b-** [comment]
The readme is actually not up to date. Firmware.bin was replaced by files in a firm/ folder that is to be moved into /rxTools/firm as @kot2002 mentioned.

**Comment by justinkb** [comment]
9.2.0-20E here. Same problem.

**Comment by urherenow** [comment]
Now I see. It's in a readme in the /tools folder. But no mention in that readme about N3ds. In any case you also need
O3ds: rxtools/firm/0004013800000002_cetk.bin
N3ds: rxtools/firm/0004013820000002_cetk.bin

**Comment by 173210** [comment]
@urherenow Old 3DS doesn't need cetk. It falls back to the old way if CETK is not available, and the way works on old 3DS, as you know.
https://github.com/roxas75/rxTools/commit/c0d9f681e11f7b1037661727a0968e4716bb7c11#diff-3d6e6ec0dc86cb98e2fabd3870eaecebR281

**Comment by justinkb** [comment]
Cherry-picked those last three commits you made @173210 in your work branch, now this issue is fixed on my side.

**Comment by urherenow** [comment]
So... What needs to be changed from rxtools/master to fix it?

**Comment by 173210** [comment]
@urherenow #271.
