### ISSUE TITLE
Canceling a NAND dump results in an STR_COMPLETED message

### ISSUE THREAD

**Issue by vgf89** [roxas75/rxTools#274]
This is confusing. It should result in an STR_FAILED message or a new STR_CANCELED message.

I'll see if I can fix this myself and start a pull request, but I'm putting this issue up for documentation purposes and comment.

**Comment by vgf89** [comment]
Also maybe the NAND.bin file should be deleted if the dump is canceled. Giving the user an incomplete NAND.bin file is useless IMO.

**Comment by 173210** [comment]
This is fixed with commit cf3ab6038fb147ac77decd0523751f7d00d26e5c in pull reqeust #283.

**Comment by capito27** [comment]
The string doesn't apear anymore if you cancel it, as such the bug is fixed, but since you suggested the automatic deletion of the wrong nand dump, i will let this issue open and relabel it as an enhancement.

**Comment by capito27** [comment]
seems like pull request #275 does exactily what i was refering to when i changed labels, then i'm closing this issue.
