### ISSUE TITLE
Dumping sysNAND never ends

### ISSUE THREAD

**Issue by vgf89** [roxas75/rxTools#276]
On my o3DS, dumping sysNAND never stops, it just keeps going and going, even extending the progress bar past the screen. I've tried to run dumps for over two hours and it never stops, or if it does, there is no indication that it completed.

**Comment by 173210** [comment]
This is fixed with commit 207b69f533807e500a0bfb02f4bb727cdd9c8799 in pull request #283.

**Comment by capito27** [comment]
O confirm this issue is fixed, therefore i'm closing this issue.
