### ISSUE TITLE
Sggestion: Remove CakeBrah

### ISSUE THREAD

**Issue by 173210** [roxas75/rxTools#284]
The reason is quite a simple: there is CtrBootManager. Even the user guide tells to use CtrBootManager for themehax.
https://docs.google.com/document/d/1vLSLAvFW_4UekzJnKCjz_ce7AWYmjp5Cq2LxfQ9cDr0

**Comment by urherenow** [comment]
But what about Ninjhax users? Doesn't rxtools.3dsx still need Cakebrah for that? This would make menuhax/browserhax a requirement.

**Comment by urherenow** [comment]
Or does the homemenu ropbin take care of that? I'm not quite sure what that's for...

**Comment by urherenow** [comment]
Also, the guide talks about using HBL...

**Comment by 173210** [comment]
@urherenow It works on Cubic Ninja and I'm using it now. :)

**Comment by urherenow** [comment]
Without Cakebrah?

**Comment by 173210** [comment]
@urherenow Yes.

**Comment by urherenow** [comment]
Cloning your tree right now to see if it will build/boot. Without Cakebrah, how is it gaining kernel access?

**Comment by 173210** [comment]
@urherenow Oh, I mean I didn't use CakeBrah in rxTools. Of course CtrBootManager includes it.

**Comment by urherenow** [comment]
Did you use Ninjhax to launch ctrbootmanager directly? That's what's confusing me. When I think of Ninjhax, I think of booting into HBL. Then rxtools would have to have Cakehax. If Ninjhax can directly boot ctrbootmanager, then that will need to be updated in the manual (but would work none the less).

**Comment by 173210** [comment]
@urherenow Yes, I did so.

**Comment by urherenow** [comment]
Ok, so building on Windows (your current tree), gets stuck with a red bottom screen when directly booting HBL through menuhax 2.0. When booting ctrbootmanager through menuhax, I can get to the rxtools menu, but whether I auto boot emunand, or manually pick SYSNAND, it halfway loads emunand and freezes (shows only a few icons and the rest never finish loading).

And for more clarification, what about booting rxtools via MSET without Cakehax? That works as well?

**Comment by 173210** [comment]
@urherenow Wait, we are talking about CakeBrah, not CakeHax, ok?

**Comment by kot2002** [comment]
Well, the CakeBrah submodule has been reverted and is quite stable on Ninjhax 1.1b, so I think this issue could be closed.
I think alternative ways(ctrbootmanager, bootctr, etc.) to boot with ninj-likehax 2.x should be written on Readme.

**Comment by AlbertoSONIC** [comment]
I guess we can close this ;)
