### ISSUE TITLE
Feature Request: Injectable for N3DS

### ISSUE THREAD

**Issue by Syphurith** [roxas75/rxTools#287]
Recently, @d0k3 had made a injectable .app and .tmd generator. And i wrote a nodejs version of it. The convertor could produce devmenu injectable.. And just today i got from @Shadowtrance that it can be used to generate a valid injectable app and tmd for his N3DS. *He tried the FBI.*
Now @d0k3 is working on implement related to Decrypt9, so users can it to dump, rebuild, and inject for new CIA to the old H&S all the steps. **I don't expect the same features here, However i want to see if there is plan for just its dump and inject steps.**
If you want to make a distributable one, you can use either the app from decrypted nand, or from unpacked decrypted CIA of H&S, along with the tmd. **However the xorpads of the H&S apps must be generated for the tool.** You can get it here: [4dsdev](http://4dsdev.org/thread.php?pid=674#674) and [gbatemp](http://gbatemp.net/threads/project-injecting-any-app-into-health-and-safety.401697/page-3#post-5784265).
Since this is feature request i don't expect this to be completed soon. *Thanks everyone.*

*EDIT:: Also to note, the injection in rxTools sometimes would mistake the version, and cause users' having two tmds inside, [See here](http://tieba.baidu.com/p/4111097949). And, if you inject A then inject B and restore, you would get A instead of H&S.*

**Comment by 173210** [comment]
I need this feature.
