### ISSUE TITLE
N3DS Fails to load NATIVE_FIRM Latest commit bee412c 

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#293]
I deleted my decrypted NATIVE_FIRM (only leaving the orig.bin file in the data folder) and rxtools will immediately say: "Failed to load NATIVE_FIRM: 4". launching from menuhax 2.0, ctrbootmanager -> /rxtools/sys/code.bin. Launching same way, but with HBL (2.5), it freezes with a red bottom screen.
Also with using Cubic Ninja with *hax 2.5. 

When launching from /rxtools/sys/code.bin, I can, however, use the advanced menu, load native_firm from SD and choose the /rxtools/data/xxxxxxorig.bin and boot into sysnand. (and in this mode, I can boot Zelda four swords... although I do legitimately own it)
Edit: When choosing to load the firm from the /dat folder, sig checks are not patched either; can't load FBI (installed as .cia) or FMP.

**Comment by kot2002** [comment]
We are no longer using ~~orig.bin workaround.

**Comment by urherenow** [comment]
So... Delete it, or remove orig from the name?

**Comment by urherenow** [comment]
The current tree has me baffled. I can find no trace of what do do with N3DS firm files. If I try placing 000401382000002.bin in the /firm folder, I get stuck on the data installation suite screen. I even tried adding 000401382000102.bin and 000401382000202.bin and their cetk files as well. Any method with placing them in /data just errors out as "Failed to load NATIVE_FIRM: 4"

**Comment by xadox-1st** [comment]
Same for me on n3DS.

**Comment by AlbertoSONIC** [comment]
It should be 

SD:/rxTools/firm/0004013820000002.bin
SD:/rxTools/firm/0004013820000002_cetk.bin

**Comment by xadox-1st** [comment]
0004013820000002.bin is the one from ReiNAND?

**Comment by kot2002** [comment]
If reinand's are not working, try cakes' (encrypted)

**Comment by xadox-1st** [comment]
Thx. Will give it a try later.

**Comment by xadox-1st** [comment]
Used the one from cakes and worked for me on.

**Comment by urherenow** [comment]
Hai. Works! Took me a bit to find one. Never thought to google the MD5 until now. Anyway, issue closed :+1:
