### ISSUE TITLE
N3DS doesn't load sysnand, emunand home screen partially loads

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#297]
Now that I have the data installation suite bit figured out, trying to boot sysnand gives me a black screen. When booting emunand, the home menu never quite finishes loading. Sometimes it just freezes, other times I can move around, but the couple of folders that it does show are empty, and the rest of my icons never load.I can currently see (but not load) a few empty folder, AR card game thingy, face raiders, and pokemon rumble world icon. That's it.

EDIT: This is booting through menuhax 2.0 and ctrbootmanager b08
EDIT2: Tried without using a theme on emunand. Also upgraded to ctrbootmanager 1.0 and tried using the yellows8 link for browserhax for good measure. Same results.
EDIT3: Looks like this issue crept in after 1edb3cd <--(last one that doesn't have this issue)

**Comment by AlbertoSONIC** [comment]
This is happening to me too. Right now I'm in the homescreen of the emunand, icons are partially loaded, background music is gone, the banner on the top screen is gone, the "Launch" button isn't showed. I can move in the menu, I tried to take a screenshot of them bottom screen (using the home menu screenshot feature) and the n3ds completely freezed. I guess there's some process9 fs service open...

**Comment by AlbertoSONIC** [comment]
It's basically like this:

-Emunand boots and arm11 loads the theme and half the icons.
-An arm9 process/thread starts using fs, so arm11 stops loading the icons and the bgm stops playing. 

@173210

**Comment by urherenow** [comment]
Almost sound right, but when using the Majora's mask theme, the music keeps playing as long as I can move around the partially loaded menu. I turned off my theme now though to eliminate is as a cause. At any rate, it never completes loading stuff from the mSD card.

**Comment by AlbertoSONIC** [comment]
@173210 I still get the same freeze on my n3ds, even with #299 :(

**Comment by urherenow** [comment]
You have to try with O3DS, as this pull was only for TWL, not the n3ds issues.

**Comment by AlbertoSONIC** [comment]
@173210 said his PR fixed this!

**Comment by 173210** [comment]
Hmm, my new 3DS can launch rxMode, and others' can't. So it should be the problem of alignment.
I found the size of a section is not aligned by 16 bits (2 bytes), so it causes the issue, I think.
But I have no idea why it does matter. I used '<' (less than) to compare the top and bottom address, so it should work...
https://github.com/roxas75/rxTools/commit/d166f5ce455eece6944d73bdd2ba7d43d3728402#diff-515bde290933b82f2f5a381e8d4a3398R191

**Comment by 173210** [comment]
Can anyone give me a result of the following command?
```
make clean
make rxmode/build/ctr/native_firm.elf
arm-none-eabi-objdump -S rxmode/build/ctr/p9_reboothax_body.o
```

**Comment by urherenow** [comment]
I'm away from my computer for like 30 hours. If it's confirmed fixed, go ahead and close, but I can't test right now...

**Comment by kot2002** [comment]
rxmode/build/ctr/p9_reboothax_body.o:     file format elf32-littlearm


Disassembly of section .text.start:

00000000 <rebootFunc>:
   0:	e92d4080 	push	{r7, lr}
   4:	e59f323c 	ldr	r3, [pc, #572]	; 248 <rebootFunc+0x248>
   8:	ee063f13 	mcr	15, 0, r3, cr6, cr3, {0}
   c:	ee153f50 	mrc	15, 0, r3, cr5, cr0, {2}
  10:	e3c3380f 	bic	r3, r3, #983040	; 0xf0000
  14:	e3833803 	orr	r3, r3, #196608	; 0x30000
  18:	ee053f50 	mcr	15, 0, r3, cr5, cr0, {2}
  1c:	ee153f70 	mrc	15, 0, r3, cr5, cr0, {3}
  20:	e3c3380f 	bic	r3, r3, #983040	; 0xf0000
  24:	e3833803 	orr	r3, r3, #196608	; 0x30000
  28:	ee053f70 	mcr	15, 0, r3, cr5, cr0, {3}
  2c:	e59f3218 	ldr	r3, [pc, #536]	; 24c <rebootFunc+0x24c>
  30:	ee063f14 	mcr	15, 0, r3, cr6, cr4, {0}
  34:	ee123f10 	mrc	15, 0, r3, cr2, cr0, {0}
  38:	e3833030 	orr	r3, r3, #48	; 0x30
  3c:	ee023f10 	mcr	15, 0, r3, cr2, cr0, {0}
  40:	ee123f30 	mrc	15, 0, r3, cr2, cr0, {1}
  44:	e3833030 	orr	r3, r3, #48	; 0x30
  48:	ee023f30 	mcr	15, 0, r3, cr2, cr0, {1}
  4c:	ee133f10 	mrc	15, 0, r3, cr3, cr0, {0}
  50:	e3833030 	orr	r3, r3, #48	; 0x30
  54:	ee033f10 	mcr	15, 0, r3, cr3, cr0, {0}
  58:	e59f31f0 	ldr	r3, [pc, #496]	; 250 <rebootFunc+0x250>
  5c:	e59f51f0 	ldr	r5, [pc, #496]	; 254 <rebootFunc+0x254>
  60:	e513c030 	ldr	ip, [r3, #-48]	; 0xffffffd0
  64:	e513e02c 	ldr	lr, [r3, #-44]	; 0xffffffd4
  68:	e5134028 	ldr	r4, [r3, #-40]	; 0xffffffd8
  6c:	e28cc309 	add	ip, ip, #603979776	; 0x24000000
  70:	e08e4004 	add	r4, lr, r4
  74:	e24cc004 	sub	ip, ip, #4
  78:	e15e0004 	cmp	lr, r4
  7c:	35bc6004 	ldrcc	r6, [ip, #4]!
  80:	348e6004 	strcc	r6, [lr], #4
  84:	3afffffb 	bcc	78 <rebootFunc+0x78>
  88:	e2833030 	add	r3, r3, #48	; 0x30
  8c:	e1530005 	cmp	r3, r5
  90:	1afffff2 	bne	60 <rebootFunc+0x60>
  94:	e3a04028 	mov	r4, #40	; 0x28
  98:	e59fc1b8 	ldr	ip, [pc, #440]	; 258 <rebootFunc+0x258>
  9c:	e59f61b8 	ldr	r6, [pc, #440]	; 25c <rebootFunc+0x25c>
  a0:	e59c3020 	ldr	r3, [ip, #32]
  a4:	e1dce3b2 	ldrh	lr, [ip, #50]	; 0x32
  a8:	e283377f 	add	r3, r3, #33292288	; 0x1fc0000
  ac:	e283390e 	add	r3, r3, #229376	; 0x38000
  b0:	e02e3e94 	mla	lr, r4, lr, r3
  b4:	e1dcc3b0 	ldrh	ip, [ip, #48]	; 0x30
  b8:	e59e5010 	ldr	r5, [lr, #16]
  bc:	e024349c 	mla	r4, ip, r4, r3
  c0:	e246700f 	sub	r7, r6, #15
  c4:	e1530004 	cmp	r3, r4
  c8:	0a00002b 	beq	17c <rebootFunc+0x17c>
  cc:	e593c008 	ldr	ip, [r3, #8]
  d0:	e31c0002 	tst	ip, #2
  d4:	0a000026 	beq	174 <rebootFunc+0x174>
  d8:	e593c004 	ldr	ip, [r3, #4]
  dc:	e35c0001 	cmp	ip, #1
  e0:	1a000023 	bne	174 <rebootFunc+0x174>
  e4:	e593c000 	ldr	ip, [r3]
  e8:	e3500000 	cmp	r0, #0
  ec:	e085c00c 	add	ip, r5, ip
  f0:	e28cc77f 	add	ip, ip, #33292288	; 0x1fc0000
  f4:	e28cc90e 	add	ip, ip, #229376	; 0x38000
  f8:	1a000008 	bne	120 <rebootFunc+0x120>
  fc:	e1a0e000 	mov	lr, r0
 100:	e7dc900e 	ldrb	r9, [ip, lr]
 104:	e7de8007 	ldrb	r8, [lr, r7]
 108:	e1590008 	cmp	r9, r8
 10c:	1a000003 	bne	120 <rebootFunc+0x120>
 110:	e28ee001 	add	lr, lr, #1
 114:	e35e000e 	cmp	lr, #14
 118:	1afffff8 	bne	100 <rebootFunc+0x100>
 11c:	ea000014 	b	174 <rebootFunc+0x174>
 120:	e3510000 	cmp	r1, #0
 124:	1a000008 	bne	14c <rebootFunc+0x14c>
 128:	e1a0e001 	mov	lr, r1
 12c:	e7dc900e 	ldrb	r9, [ip, lr]
 130:	e7de8006 	ldrb	r8, [lr, r6]
 134:	e1590008 	cmp	r9, r8
 138:	1a000003 	bne	14c <rebootFunc+0x14c>
 13c:	e28ee001 	add	lr, lr, #1
 140:	e35e000f 	cmp	lr, #15
 144:	1afffff8 	bne	12c <rebootFunc+0x12c>
 148:	ea000009 	b	174 <rebootFunc+0x174>
 14c:	e593c00c 	ldr	ip, [r3, #12]
 150:	e5939010 	ldr	r9, [r3, #16]
 154:	e5938014 	ldr	r8, [r3, #20]
 158:	e59fe100 	ldr	lr, [pc, #256]	; 260 <rebootFunc+0x260>
 15c:	e08c8008 	add	r8, ip, r8
 160:	e089e00e 	add	lr, r9, lr
 164:	e15c0008 	cmp	ip, r8
 168:	31fe90b2 	ldrhcc	r9, [lr, #2]!
 16c:	30cc90b2 	strhcc	r9, [ip], #2
 170:	3afffffb 	bcc	164 <rebootFunc+0x164>
 174:	e2833028 	add	r3, r3, #40	; 0x28
 178:	eaffffd1 	b	c4 <rebootFunc+0xc4>
 17c:	e3500000 	cmp	r0, #0
 180:	159f30dc 	ldrne	r3, [pc, #220]	; 264 <rebootFunc+0x264>
 184:	15830000 	strne	r0, [r3]
 188:	e3510000 	cmp	r1, #0
 18c:	1a000002 	bne	19c <rebootFunc+0x19c>
 190:	e59f30d0 	ldr	r3, [pc, #208]	; 268 <rebootFunc+0x268>
 194:	e59fc0d0 	ldr	ip, [pc, #208]	; 26c <rebootFunc+0x26c>
 198:	ea000006 	b	1b8 <rebootFunc+0x1b8>
 19c:	e59f00cc 	ldr	r0, [pc, #204]	; 270 <rebootFunc+0x270>
 1a0:	e2403010 	sub	r3, r0, #16
 1a4:	e1530000 	cmp	r3, r0
 1a8:	2afffff8 	bcs	190 <rebootFunc+0x190>
 1ac:	e491c004 	ldr	ip, [r1], #4
 1b0:	e483c004 	str	ip, [r3], #4
 1b4:	eafffffa 	b	1a4 <rebootFunc+0x1a4>
 1b8:	e5931004 	ldr	r1, [r3, #4]
 1bc:	e5930008 	ldr	r0, [r3, #8]
 1c0:	e0810000 	add	r0, r1, r0
 1c4:	e1510000 	cmp	r1, r0
 1c8:	2a000002 	bcs	1d8 <rebootFunc+0x1d8>
 1cc:	ee071f3a 	mcr	15, 0, r1, cr7, cr10, {1}
 1d0:	e2811020 	add	r1, r1, #32
 1d4:	eafffffa 	b	1c4 <rebootFunc+0x1c4>
 1d8:	e2833030 	add	r3, r3, #48	; 0x30
 1dc:	e153000c 	cmp	r3, ip
 1e0:	1afffff4 	bne	1b8 <rebootFunc+0x1b8>
 1e4:	e3a03000 	mov	r3, #0
 1e8:	ee073f9a 	mcr	15, 0, r3, cr7, cr10, {4}
 1ec:	e3a01309 	mov	r1, #603979776	; 0x24000000
 1f0:	e5911008 	ldr	r1, [r1, #8]
 1f4:	e5821000 	str	r1, [r2]
 1f8:	ee072f3a 	mcr	15, 0, r2, cr7, cr10, {1}
 1fc:	ee073f9a 	mcr	15, 0, r3, cr7, cr10, {4}
 200:	e59f3060 	ldr	r3, [pc, #96]	; 268 <rebootFunc+0x268>
 204:	e59f0060 	ldr	r0, [pc, #96]	; 26c <rebootFunc+0x26c>
 208:	e593200c 	ldr	r2, [r3, #12]
 20c:	e3520000 	cmp	r2, #0
 210:	05932004 	ldreq	r2, [r3, #4]
 214:	05931008 	ldreq	r1, [r3, #8]
 218:	00821001 	addeq	r1, r2, r1
 21c:	1a000004 	bne	234 <rebootFunc+0x234>
 220:	e1520001 	cmp	r2, r1
 224:	2a000002 	bcs	234 <rebootFunc+0x234>
 228:	ee072f35 	mcr	15, 0, r2, cr7, cr5, {1}
 22c:	e2822020 	add	r2, r2, #32
 230:	eafffffa 	b	220 <rebootFunc+0x220>
 234:	e2833030 	add	r3, r3, #48	; 0x30
 238:	e1530000 	cmp	r3, r0
 23c:	1afffff1 	bne	208 <rebootFunc+0x208>
 240:	e3a03309 	mov	r3, #603979776	; 0x24000000
 244:	e593f00c 	ldr	pc, [r3, #12]
 248:	10000035 	.word	0x10000035
 24c:	18000035 	.word	0x18000035
 250:	24000070 	.word	0x24000070
 254:	24000130 	.word	0x24000130
 258:	01ff8000 	.word	0x01ff8000
 25c:	0000000f 	.word	0x0000000f
 260:	01ff7ffe 	.word	0x01ff7ffe
 264:	00000000 	.word	0x00000000
 268:	24000040 	.word	0x24000040
 26c:	24000100 	.word	0x24000100
 270:	00000010 	.word	0x00000010

**Comment by 173210** [comment]
Please tell me whether 261aad518645717532977872b1a610a4a79daa85 works or not.

**Comment by kot2002** [comment]
That commit makes difference here :
```
 168:	35fe9001 	ldrbcc	r9, [lr, #1]!
 16c:		34cc9001 	strbcc	r9, [ip], #1

...

 260:	01ff7fff 	.word	0x01ff7fff
```
I cannot test on N3DS, so I posted this instead.
It works on O3DS perfectly and I cannot find any bugs right now.

**Comment by urherenow** [comment]
Just got home. Latest tree with the above patch already in it, has the same issue. I started from scratch again and it took several tries to even get to the installation data part (kept freezing as soon as I hit X in the ctrboot manager). Trying ctrbootmanager->HBL 2.5->rxtools results in a black upper screen and red bottom screen.

**Comment by 173210** [comment]
@urherenow This issue is for the problem of the rxMode, so you should open another issue if you have a different problem.
By the way, are you trying to boot with CakeBrah? CakeBrah in rxTools doesn't support HBL 2.5.

**Comment by urherenow** [comment]
I'm using menuhax 2.0->ctrbootmanager 1.0->/rxtools/code.bin. All I did was clone the current tree and make release, so if cakebrah was removed, then I'm not using it. With the above method, rxmode sysnand freezes. rxmode emunand doesn't finish loading the home menu. I can move around until I try to launch something, then it freezes. I know what the issue is. I'm the one who opened it!

**Comment by 173210** [comment]
@urherenow So you have a problem when launching rxMode after you used ctrbootmanager to boot rxTools?

**Comment by urherenow** [comment]
yes

**Comment by urherenow** [comment]
shall I revert back to ninjhax 1.1b and try again?

**Comment by 173210** [comment]
@urherenow It works fine with *hax 2.5 and ctrbootmanager on my new 3DS, so I don't think it matters.

**Comment by kot2002** [comment]
I am even thinking that your build environment might be somewhat special..

**Comment by 173210** [comment]
@kot2002 Actually I have only tested @Matsumot0's binary for old one. I know that this problem is different from the issue occurred on old one thanks to @urherenow, so I may have to test others' binary.
Can anyone give me a binary with the issue?

**Comment by kot2002** [comment]
https://mega.nz/#!I1xXnTSR!0cWu7_ig1UGEhhm0qT628SO5fg5HNBFNA3S2z1U2HxA
261aad518645717532977872b1a610a4a79daa85

**Comment by urherenow** [comment]
More info: on emunand, I cannot even attempt to launch anything with the A button. I have to tap on an icon, then it will freeze if it's an app, or if it's a folder, it will open an empty folder. sysnand... just immediately freezes. It can't be my build environment. Others on gbatemp have tried from the lavanoid link and have the same issue.

**Comment by kot2002** [comment]
@urherenow I don't think ctrulib makes incompatiblity. It is not used except for CakeBrah.

**Comment by Matsumot0** [comment]
@kot2002 +1 =)

**Comment by 173210** [comment]
@kot2002 Thanks for the binary. Well, it works on my new 3DS, both on sys and emu NAND. So what can I do to fix it? :(

**Comment by urherenow** [comment]
What region is your N3DS? Maybe the problem is a difference in (a) offset(s) for something that is different between regions?

**Comment by kot2002** [comment]
That is really odd. Probably the others may be using corrupted firmware files? I am confused either.

**Comment by 173210** [comment]
@urherenow J, of course.
@kot2002
```shell-session
root3@root3-X230t:~$ md5sum rxTools/firm/0004013820000002.bin
b99adf0adb279712367c06eb83ba9ae6  rxTools/firm/0004013820000002.bin
```

**Comment by urherenow** [comment]
I doubt it. Any other firmware file or cetk, and it will not get past the data installation screen.

**Comment by 173210** [comment]
@urherenow It works thanks to 79f7b9b26236d5e44ace4aacd1b7897c2bdcbe84.

**Comment by kot2002** [comment]
0004013820000002_cetk.bin
0004013820000002_cetk 
which is right one?

**Comment by 173210** [comment]
@kot2002 `0004013820000002_cetk.bin` is. But it's not necessary.

**Comment by urherenow** [comment]
Hmm... but it does have an effect. Like I said, When trying a cetk someone posted the md5 for, I was getting nowhere. I had to grab the latest cetk to get past data installation. During my lunch, I'll try again without the cetk. And I will kick myself if that solves the problem...

**Comment by urherenow** [comment]
It DOES work without the _cetk.bin (data installation). But it still has the same issue. Mine is a USA N3DS. I thought the cetk was being used to get a decryption key of some kind... so why does the install work? Why does the O3DS use 3 /firm files but N3DS only uses 1? (I know the other two are TWL and AGB, but just trying to spark a thought process to figure out what is happening here)
Either way, from what we know so far, the only difference is the region. How can I help? Can I run Gateway emunand, run BootNTR and use the debugger client to check the PIDs and offsets to compare with the JPN model?

**Comment by 173210** [comment]
@urherenow The decryption key can be extracted from NAND. It simply skipps TWL and AGB decryption.
We use the same FIRM even though the region differs. Although it has an ARM11 patch, I don't think it matters. If you suspect that, comment out this line.
https://github.com/roxas75/rxTools/commit/63cc9bfac815018b3af40f4bf943b6a6bb7bc33a#diff-aea7b59ab1139341532e385b49364e0fR19
```GAS
	.word	hook
```

**Comment by urherenow** [comment]
Sorry; Didn't work. Commented out only that 1 line ->make clean->make release, then replaced everything in /rxtools/sys. Same issue.

**Comment by kot2002** [comment]
I know you would've, but to be sure. Did you erase rxTools/data directory?

**Comment by urherenow** [comment]
Each time :P. It took a few tries to get rxtools to boot into the data installation screen though. ctrbootmanager kept locking up on me until I just kept holding L until it timed out and booted rxtools. Still, commenting out that 1 line did nothing to help :(

**Comment by 173210** [comment]
I forgot to mention the label patch. It can be disabled by commenting out this line.
https://github.com/roxas75/rxTools/commit/ee0741469682a7003f048bb8909bd1bda5c4ecaf#diff-2a50eddb55fc9cb6fd8ba1278ca1bb76R34
```
	svc 0x8
```

**Comment by 173210** [comment]
By the way, you can use "Labels" to show this is critical.

**Comment by kot2002** [comment]
CRITICAL BUG... LOL

**Comment by 173210** [comment]
@kot2002 Yes, it's critical for all new 3DS owners...except me LOL

**Comment by urherenow** [comment]
Not sure that the LOL is for. I can't seem to add a label. Perhaps since I'm not a contributor? I dunno. If the LOL was because I said critical... there are bugs that aren't critical. Don't think the guys who made SMB intended for us to walk through walls, or get a flower that turns us small while we can still shoot fireballs... But that's cool, not critical.

Anyway, commenting out svc 0x8 doesn't completely fix it, but it does do something! The emunand home screen now loads completely. It just freezes when trying to launch something. Now sysnand behaves the same way that emunand behaved before commenting out that line (not all icons load, and can't launch something that did load with the A button. Tapping the icon freezes the console, but the bgm keeps playing.
I did uncomment the hook line, so I guess I'll go back and try again with both items commented out.

**Comment by urherenow** [comment]
It works even less with both hook, and svc 0x8 commented out. Best case so far, is only commenting out svc 0x8, then you can at least load emunand and play some legit stuff on it. Sysnand is still screwed though, and so are sig patches.

**Comment by urherenow** [comment]
Ok. for sure, the problems started with build fafa618. Two major things happened in this build:
1) We switched from Reinand's decrypted firmware in /data, to Cake's encrypted firmware in /firm
2) /sys/patches no longer has a CTR and KTR folder.

Sure, build 1edb3cd had issues we'd like to fix, but that's the last useable build on N3ds.
I'm done playing around for the day. My wife wants to get out of the house, and I have college work to do with an all-day engagement on my schedule Sunday :(

**Comment by 173210** [comment]
@AlbertoSONIC Have you confirmed #303 fixes this?

**Comment by urherenow** [comment]
He couldn't have. His N3DS was apparently the only one without a problem. I question whether he deletes his /data folder when testing new builds... I'll be able to confirm within 2 hours.

**Comment by AlbertoSONIC** [comment]
@173210 Nope I didn't! I don't know why github closed this for me!

@urherenow My N3DS has this problem! It's 173210's one to be working ;)

**Comment by AlbertoSONIC** [comment]
@urherenow Also, deleting /data folder is just useless as rxTools checks if the data folder is up to date with latest patches (in sys) at every boot

**Comment by 173210** [comment]
So once if you removed data directory after 2c385888db86d12bb2769f54d872ee373ff554ba, it should be fine.
Also note that it will regenerate firmwares if data.bin, used in the older version, is in SDMC.

**Comment by urherenow** [comment]
Not quite fixed. emunand seemed to be working, but froze when trying to launch freemultipatcher. Not sure if it's a sig check problem or not.

**Comment by AlbertoSONIC** [comment]
Now It's fixed :)

**Comment by kot2002** [comment]
Great job! Both @AlbertoSONIC and @173210 !

**Comment by urherenow** [comment]
My troubleshooting must have helped at least a little, right? I was fairly sure on my last comment that the final problem was the sig patch, but I've been busy and even if I tried to fix it myself, I still have no clue the proper way to do a pull request. 

One thing I still don't understand though... without loading any *Hax or cfw or anything, sysnand won't lock up simply for hovering over an unofficial app. So why was the cfw behaving that way?

Anyway, thanks for the fix!

**Comment by 173210** [comment]
Thank you, @AlbertoSONIC and all who investigated the issue.
@urherenow Yes, I figured out the issue thanks to your information and told @AlbertoSONIC the detail.
The old code jumped to "somewhere" unknown. It could lead to anything. LOL

**Comment by urherenow** [comment]
"The old code jumped to "somewhere" unknown. It could lead to anything. LOL"

Oh, right. That could definitely wreak havoc!
