### ISSUE TITLE
Pasta Mode broken on N3DS

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#304]
Menu freezes as soon as you press A on pasta mode in the advanced menu.

**Comment by motezazer** [comment]
It's because Pasta Mode for N3DS, who was implemented recently, was removed for legal reasons.
And I forgot to commit the new one.

**Comment by urherenow** [comment]
Forgot to commit? So you already have it taken care of, minus a pull request? Sounds promising 👍

**Comment by motezazer** [comment]
I just have to test if it doesn't conflict with the latest commits.

**Comment by motezazer** [comment]
It should be fixed now. Can you test? I forgot Cubic ninja at home.

**Comment by urherenow** [comment]
Seems to work! Awesome! Closing :)
