### ISSUE TITLE
decryptFirmKtrArm9: Search for ARM9 partition with isArm11

### ISSUE THREAD

**Issue by 173210** [roxas75/rxTools#311]
In the current code, the number of ARM9 partition is hard-coded in decryptFirmKtrArm9.
However, the partitions in AGB and TWL FIRM are in different segments.
I suggest to search them with isArm11 flag.

https://github.com/roxas75/rxTools/commit/920e334b0da06385506e965d00ac4a8e2e0e7993#diff-da79e5a9eafcb6d28e0f37207aaf39e4R91
```
	hdr = (void *)(p + ((FirmHdr *)p)->segs[2].offset);
```

**Comment by motezazer** [comment]
What is this function?
It's implementation was useless, I already implemented such a fonction (without this problem) with commit c1a3784514ae017f9f7c09013601668bbb0e19b0 !

**Comment by urherenow** [comment]
That commit only makes things work for Pasta mode (and I want to say the already do work, but my DSi and GBA stuff is all legit anyway). @173110, are you trying to get things working in emunand?

**Comment by urherenow** [comment]
Damn typos... The=they, and of course @173210

**Comment by 173210** [comment]
@motezazer @AlbertoSONIC had already made it before you make with commit 79f7b9b26236d5e44ace4aacd1b7897c2bdcbe84, although it's not an independent function.

/*
I prefer @AlbertoSONIC's one because his uses structure and existing functions.
*/

@urherenow Yes.
