### ISSUE TITLE
progress numbers are not properly updated in the Nand Partitions dumping screen

### ISSUE THREAD

**Issue by capito27** [roxas75/rxTools#312]
In the nand partitions dumping screen, whenever there is any progress, the displayed progress values  will be overwritter instead of being cleared and then written.

**Comment by Syphurith** [comment]
@capito27 Maybe Most Simply solution: paint extra spaces to clear the whole line.

**Comment by 173210** [comment]
@Syphurith Now it can use `\033[K` instead of that.

**Comment by AlbertoSONIC** [comment]
It's a dirty fix but it works so yeah
