### ISSUE TITLE
DS carts not working on emuNAND with SysNAND 4.X

### ISSUE THREAD

**Issue by MelonGx** [roxas75/rxTools#314]
But it works on emuNAND with SysNAND 9.X.

My test:
O3DS A - Sys 9.2.0-20J, Emu 10.3.0-28J, RX Nov.15/Nov.19/Oct.02, Menuhax booting - Run DS cart properly
O3DS B - Sys 4.5.0-10J, Emu 10.3.0-28J, RX Nov.15/Nov.19/Oct.02, DS profile booting - "An error occured"

DS carts:
legitimate carts, MT-card bluecard, DSTWO

Don't know how N3DS is.

(Edit) Since the project has announced that rxMode only supports TWL (DS carts/DSiWare) on SysNAND, I'm doubting if I need to close this issue.

**Comment by urherenow** [comment]
Yes, you should close it. Do DS carts run on SYSNAND on your 4.x without using rxtools? Did you install GW's blue card fix on your 4.x system's emunand? (or flashcardtimewarp, which is the same thing, I guess).

Either way, there is no reason not to use SYSNAND for DS/GBA/DSi stuff. Rxtools DEVs have more important things to bother with.

**Comment by ApacheThunder** [comment]
Yeah, 4.x with working TWL on emunand is pretty low priority. Only people this could have affected are those using menuhax that autoboots them to emunand. But 9.x sysnand is needed for that and I hear TWL from slot-1 works on emunand, so really a non issue right now. :P

**Comment by MelonGx** [comment]
Someone reported that DS carts work on rxTools Oct.02 but not work on later and latest versions.
After I confirm that I'll start a new issue about it.
Now I close this issue.

**Comment by MelonGx** [comment]
The post above is talking about N3DS.
