### ISSUE TITLE
Reproducable crash on Home Menu

### ISSUE THREAD

**Issue by matthewpetch** [roxas75/rxTools#315]
New 3DS 9.1J, running RXTools on 9.5j emunand

Tried various nightlies, all of which are from the past month. Only one I haven't tried was the latest 5th December nightly which I couldn't get running for some reason.

When my Home Menu is on the grid system (where there's 20 or so tiles on the bottom screen) and I move the selected tile right with the d-pad, the system will freeze once I make it to the first 'tile' of the next screen. This happens every time. Haven't tested with other screen layouts yet.

**Comment by gudenau** [comment]
Happens to me as-well.

**Comment by matthewpetch** [comment]
If my description isn't clear enough I'll be happy to make a video to demonstrate. 

Will also test on O3DS (EU) later this week...

**Comment by AlbertoSONIC** [comment]
If you can ;)

**Comment by matthewpetch** [comment]
https://www.youtube.com/watch?v=ubi1xvOuEaM

**Comment by AlbertoSONIC** [comment]
WTF?! I'll try to replicate it, but in the mainwhile @173210 any clue about why does this happen?

**Comment by 173210** [comment]
Nothing. I can say only the following thing: it works fine on my new 3DS (378e20bc44e8c0193cd93bc45108a750e11a7a5e).

**Comment by AlbertoSONIC** [comment]
Well it never happened on my n3ds too.... Maybe because my home is full of icons... let me try to copy the video's home...

**Comment by AlbertoSONIC** [comment]
No freeze! I can't replicate this bug!
Il giorno sab 12 dic 2015 alle 06:35 173210 <notifications@github.com> ha
scritto:

**Comment by urherenow** [comment]
That leaves 3 questions... What's the OP'scard speed, is it fragmented, and what kind of mismatched firmware files does he have on that NAND?

**Comment by hartmannaf** [comment]
I read about an issue like this somewere a time ago, there it was a problem with the signature patching. So I Think he may use the wrong firmware file.

**Comment by AlbertoSONIC** [comment]
@hartmannaf If the sigcheck patch was wrong, it would have frozen when highlighting an custom cia, not on an empty box...

**Comment by hartmannaf** [comment]
In his video it stopped showing the banner after he was over an Custom cia.

**Comment by AlbertoSONIC** [comment]
Well I noticed it now. Then you may be right... But why can't I replicate it?

**Comment by hartmannaf** [comment]
He could give us the firmwares md5, and his rxtools folder, then we could check them.

**Comment by matthewpetch** [comment]
Emunand was created from 8.1j originally, updated to 9.5 as normal in system settings.

MicroSD is Samsung, 64GB UHS-1

Currently using 5/12/15 release
/rxtools/firm/0004013820000002.bin MD5: B99ADF0ADB279712367C06EB83BA9AE6
/rxtools/firm/0004013820000002_cetk.bin MD5: B4721A5B6105C2D33A082E22F3F2A2F4
/rxtools/data/0004013820000002.bin MD5: 36C0CF280D4798805A0CDFD27463FAA2

I think I used the Reinand .bin at one point but I either couldn't get it to work at all or it had the same problem, can't remember honestly

**Comment by AlbertoSONIC** [comment]
A guy from gbatemp told me this:

"Not a bug. You have the mSD utility installed. That is using a 0 paired key which doesn't work correctly on rxTools. It does work perfectly fine with Gateway"

**Comment by matthewpetch** [comment]
Ah, mystery solved then. It does seem to work fine when I boot NTR from RXtools, but then I get a seemingly random crash when moving around the home menu (not very frequent).

**Comment by Syphurith** [comment]
@AlbertoSONIC If a CIA is signed with key0 before you can rebuild it to Unencrypted.

**Comment by urherenow** [comment]
By the way @matthewpetch, n3ds doesn't need the cetk.

**Comment by urherenow** [comment]
Actually, I seriously doubt it's a problem with zero key encryption because that utility runs just fine under rxtools on an N3DS. The same .cia installed on an o3ds reproduced the crash here (but works a treat using GW).

My guess, is that it's actually a kernel check thing. Seems only GW has that on lockdown.
