### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by gudenau** [roxas75/rxTools#318]
When booting into a 9.5.0-28U emuNAND with the latest nightly on a n3DS the home menu freezes before it can load all of it's assets. When using an older build it works just fine, I forget which one it is.

**Comment by urherenow** [comment]
do you have a /firm folder with 0004013820000002.bin in it? If so, it's probably the decrypted one from reinand. The latest build requires the encrypted one from Cakes. Just search the web for the md5:
B99ADF0ADB279712367C06EB83BA9AE6
then close this issue.

**Comment by gudenau** [comment]
Where am I supposed to put that and what should I name it?

**Comment by urherenow** [comment]
does the md5 match what I posted?

**Comment by gudenau** [comment]
Yes.

**Comment by urherenow** [comment]
delete your rxtools/data folder and try again

**Comment by gudenau** [comment]
That does not exist.

**Comment by AlbertoSONIC** [comment]
Enable hidden files in Windows Explorer settings

**Comment by gudenau** [comment]
I always have that enabled.

**Comment by gudenau** [comment]
Hashes:
b99adf0adb279712367c06eb83ba9ae6 *firm\0004013820000002.bin
2a4c62de1e564d8d8647306aedfe0793 *lang\en.json
9b753f2b26f6eed51dff7b94c9789b16 *lang\es.json
657ecc8d47b9ef0620666b1819215788 *lang\fr.json
63ae9f4f79c14e5e86b8c76cb8941105 *lang\hr.json
f85a3bfa7a8e1391faa3efff8c681ca0 *lang\it.json
3dbbef31064c3b10a87e331f69f6a350 *lang\ko.json
eb89b99c3279e66ee2b4c200b8d599df *lang\nl.json
96933ab529e92a6b670a5206903a7e95 *lang\no.json
33b8d3fbeceba9de07346017bda5e679 *lang\pt.json
f08d71fd659bc47e83428c0c07163175 *lang\ru.json
fcd725c0e9ca00bbfb2ed5b16ff900e0 *lang\zh-CN.json
27c5ebaadd9112c787a2b811b1006469 *lang\zh-TW.json
b2ac1c037f89ffcc01fd7ce88c280142 *sys\code.bin
6555097c97038a47e566bbb774664d1c *sys\font.bin
f92f929b9c9a3ee06bd3fb72ecd12bed *sys\reboot.bin
87fa78f6a5ce1c4fb2f1dcac6b47b76a *sys\patches\0004013800000002.elf
e99011ece67f6697385a779173f853f6 *sys\patches\0004013800000102.elf
839dc6ba0341070777b9863d1c8c9ba8 *sys\patches\0004013800000202.elf
11505da86e2a49202b1f71e6a2374efb *sys\patches\0004013820000002.elf
6df3f8c9931091a866fa8210ce0242d0 *theme\0\adv0.bin
13be318780ee738a200e7dc28ce341f6 *theme\0\adv1.bin
b33ba07d87cbb438c53c866880ff0789 *theme\0\adv2.bin
86faa8a2ce18dbba62d7a6bc971684a6 *theme\0\adv3.bin
c4fed67dadda543521405f3ab039553c *theme\0\adv4.bin
8be85da9e3fd4e32070fb1ef2e14d6c6 *theme\0\app.bin
02911554b883e69088f22d7ecee3dc33 *theme\0\BASE.bin
b3accbfe0104bd188ba7ea8f38089ca3 *theme\0\boot.bin
af49b0b50016ae29d8324625a4324f5a *theme\0\boot0.bin
56161912e27cdf353b697a455ff19d96 *theme\0\bootE.bin
159634df386a2b4b11ce6e295ff26079 *theme\0\bootS.bin
4ed5ac7e3a7b3aa19818d44ce0ecda79 *theme\0\cfg0.bin
604a8f43713fce8dc1bec170f4860e56 *theme\0\cfg0TOP.bin
685d67a04beb1695164259f6ef60f720 *theme\0\cfg1E.bin
4c2f40acbff208b27a0d46ec521c0f79 *theme\0\cfg1O.bin
925bbe7714886d5ab8df5000908c518e *theme\0\credits.bin
e385b82102204189093d11021087e2ad *theme\0\dec0.bin
a103762cc18905b853238526ef2570be *theme\0\dec1.bin
5b406dd73248ff5100845a896b98efc9 *theme\0\dec2.bin
334e43f4f386a4bd5c8ec34c7b73e261 *theme\0\dec3.bin
8fd922b67756ec11d806c4f30f857d11 *theme\0\dec4.bin
a6e53ae48b477590639fe57c3405b78f *theme\0\dec5.bin
2ea5650c1a0ab2eaf1d9469472473230 *theme\0\dmp0.bin
37e391934d4632c48f80690e821c0f4e *theme\0\dmp1.bin
fb70d482454d1677c86612d21534feeb *theme\0\dmp2.bin
a72224e4ed061c3b76945d7371f98bf0 *theme\0\dmp3.bin
46751db8cf4da4701a3afa238cd6926e *theme\0\fil0.bin
676d6764626b2fd4a568dcfc6c8220a2 *theme\0\fil1.bin
7c4209ba475052b6660c61517f0773ed *theme\0\fil2.bin
9262a293b89301c1320af8129767a3f7 *theme\0\fil3.bin
eb6fd249997c45a49a5390750c1d356b *theme\0\fil4.bin
c669e310583c2d0c62f7b1955d8965ec *theme\0\fil5.bin
86dcccd95d8bcab40ab8407108e44f63 *theme\0\inj0.bin
94de683e6751639f39145e8b1b09f0f6 *theme\0\inj1.bin
20abffe09120199df05cfd4d6577289c *theme\0\LANG.txt
568f99792e0a2b2d11eca6fce67c8823 *theme\0\menu0.bin
07667f05f5abca06e9bf69824c0c1b3d *theme\0\menu1.bin
cb8ec669c623478a4adb3bcc9341cb6e *theme\0\menu2.bin
1ef540fab9e0ced794ad906fd1f200b7 *theme\0\menu3.bin
42c1695e23be4eebd0ce5be9ea6009f4 *theme\0\menu4.bin
b75ca1d7519071dccd6482281c0439cf *theme\0\menu5.bin
a61b20f2baa66364d925c5a662cbec0f *theme\0\menu6.bin
b86ced93574a36f9a26d6e4f07b4381d *theme\0\themetool.bat
0b6b8d57acbfbaf0531f262bca63c746 *theme\0\themetool.sh
8a1d16a571ef3a92e20f02091284dba1 *theme\0\TOP.bin

**Comment by urherenow** [comment]
works fine here. You might have a messed up SD card (try doing a FULL format with sdformatter after copying your stuff, then copy it back.There is no way you are booting into your home menu in rxmode without having an rxtools/data folder. That's where your native_firm goes after rxtools decrypts it. Without that, there is no 9.5 emunand.

**Comment by gudenau** [comment]
I did delete the rxtools folder before attempting to update, I will try a format.

**Comment by gudenau** [comment]
Seemed to work, then the home menu crashes and relaunches every few seconds.

**Comment by urherenow** [comment]
Maybe. Didn't menuhax suggest starting with a regular theme? Then there is a theme manager in the starter kit you can use after that, iirc.

Also, don't forget all of those hax have recently been updated, so it might be better to download the starter pack again and set it all up from scratch. Either way, I think you can close this issue.

**Comment by gudenau** [comment]
It seems that the problem I was having has been fixed.
