### ISSUE TITLE
Update Cakebrah and Cakehax for devkitARM R45

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#320]
I don't see how to add a label on my phone. This is probably a request or enhancement. I *might* have time to look into it myself the 27th. No promises though. If an actual dev wants to do it faster, please do so.

**Comment by urherenow** [comment]
Well, crap. The first show stopping change that's needed is in Cakehax. When @173210 made some changes, the Cakehax person didn't want to merge his work. So should I even bother with this right now?

**Comment by SoujiSeta** [comment]
The codes changes for libkhax has been documented already by Kyokyonos
https://github.com/Steveice10/citrus/issues/7#issuecomment-162272219

**Comment by mariogamer2** [comment]
I tryed to merge latest commit of CakeBrah but its doesn't work,does this is normal?

**Comment by urherenow** [comment]
manually fixing on my end doesn't help because this stuff is not forked. It is included as a submodule. At any rate, libkhax is ok, but now I'm dealing with : 
[code]
x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/brahma.c:23:1: error: unknown type name 'GSP_FramebufferInfo'
 GSP_FramebufferInfo topFramebufferInfo, bottomFramebufferInfo;
 ^
x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/brahma.c: In function 'priv_firm_reboot':
x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/brahma.c:347:38: error: request for member 'framebuf0_vaddr' in something not a structure or union
     save[0] = (u32)topFramebufferInfo.framebuf0_vaddr;
                                      ^
x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/brahma.c:348:38: error: request for member 'framebuf1_vaddr' in something not a structure or union
     save[1] = (u32)topFramebufferInfo.framebuf1_vaddr;
                                      ^
x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/brahma.c:349:41: error: request for member 'framebuf0_vaddr' in something not a structure or union
     save[2] = (u32)bottomFramebufferInfo.framebuf0_vaddr;
[/code]
I don't know much about cpp...

**Comment by 173210** [comment]
So ctrulib is broken? LOL

**Comment by urherenow** [comment]
no, cakebrah is broken

**Comment by mariogamer2** [comment]
& Cakehax?

**Comment by urherenow** [comment]
Cakehax was an easy fix

**Comment by urherenow** [comment]
wait... I didn't have the latest cakehax updates. Now the build is fine with only 1 warning:

x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/libkhax/khaxinit.cpp: In destructor 'KHAX::MemChunkHax::~MemChunkHax()':                                x:/devkitPro/devkitARM/projects/rxTools/CakeBrah/source/libkhax/khaxinit.cpp:931:12: warning: unused variable 'res' [-Wunused-variable]
     Result res = svcControlMemory(&dummy, reinterpret_cast<u32>(&m_overwriteMemory->m_pages[x]), 0,

**Comment by mariogamer2** [comment]
Trying to make rxTools with latest devkitARM doesn't work at all...

**Comment by urherenow** [comment]
delete the Cakebrah and Cakehax folders, then clone and build them separately. Then run make release from rxtools and it will build fine then.

**Comment by urherenow** [comment]
In the meantime, the required change for the memset issue is to add the function to cakehax main.c:

 7       +void memset(void *dest, int filler, uint32_t size)  
 8   +{  
 9   +    char *destc = (char *)dest;  
 10   +    for (uint32_t i = 0; i < size; i++) {  
 11   +        destc[i] = filler;  
 12   +    }  
 13   +}  
 14   +

**Comment by urherenow** [comment]
Never mind this for now. Building under r45 with the needed changes to Cakehax and Cakebrah under ctrulib 1.0 completely breaks rxtools on N3DS. Closing for now.

**Comment by mariogamer2** [comment]
This not make all things,like rxtools ninjhax in build/release

**Comment by urherenow** [comment]
because you're using the latest source. The makefiles have been messed with. If you want to do it, you need to use the dec 5 source.
