### ISSUE TITLE
Fix compiler warning (initializer-string too long)

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#323]
source/MainMenu.h:85:5: warning: initializer-string for array of chars is too long
   { L" Install FBI over Health&Safety App", &installFBI, "adv1.bin" },
     ^
source/MainMenu.h:85:5: note: (near initialization for '(anonymous)[1].Str')
source/MainMenu.h:86:5: warning: initializer-string for array of chars is too long
   { L" Restore original Health&Safety App", &restoreHS, "adv2.bin" },

Changing Health&Safety to "H&S" takes care of it, but I don't know if you'd want it that way. I'm not sure if this can cause any issues, but isn't the injection still broken for some reason on either the o3ds or n3ds?

**Comment by AlbertoSONIC** [comment]
Fixed in 895bf35
