### ISSUE TITLE
FBI won't inject

### ISSUE THREAD

**Issue by mariogamer2** [roxas75/rxTools#335]
With latest Nightly,when injecting FBI,it simply give me (this is for all choice):

Opening S...
Failed!
Opening S...
FAiled!

**Comment by Syphurith** [comment]
@mariogamer2 I'm sorry for that, but this FBI injection should only work on O3DS now. If you've seen opening S then there should be something wrong related to string operations. Eh..

**Comment by Syphurith** [comment]
Problem found. In `en.json` or maybe more language files. Since we're now using Unicode, the string printing should use `%ls` instead of `%s`. `	"OPENING": "Opening %s...\n",`.
Also this could be more complicate than I think.. If you want just edit the en.json for the %ls and retry.

**Comment by urherenow** [comment]
Wait... Are you sure it's fixed? What about N3DS?

**Comment by AlbertoSONIC** [comment]
I fixed a bug, I don't know n3ds side...

**Comment by capito27** [comment]
As for the N3DS side of it, there are a few things to add to the code (like
the title ID of the N3DS H&S) but the biggest issue is that we need the FBI
APP and TMD for those N3DS H&S to be generated, and I don't have enough
time to do the latter (I guess I could push the former in a few hours,
once  I get home)

**Comment by Syphurith** [comment]
@capito27 If you want to generate the injectable FBI for N3DS, or for other tool,
> Get my script first : http://pan.baidu.com/s/1hqEsBWw Nodejs
> Just follow the operation described in the text in the zip you should be ok to get a injectable one.

And for end-users you can either use scripts or just use Decrypt9 to inject anything you want.

@AlbertoSONIC I'm sorry but there is more `%s` instead of `%ls` in those `.json` and also you can find quite many if you grep-ed the source code for `%s` (for me a windows user now i used astrogrep)

**Comment by AlbertoSONIC** [comment]
@Syphurith Yeah I know I just fixed FBI ;)

**Comment by urherenow** [comment]
Should I open a new issue for N3DS? Injecting isn't needed since NASA can be used to install FBI.cia, even from emunand 10.3 (o3ds or Cakes/ReiNand on n3ds), but if it will remain included, then it should be fixed for N3DS. rxTools currently does not find the TMD.
