### ISSUE TITLE
Now new3ds use rxtools enumNAND support 10.3?

### ISSUE THREAD

**Issue by ai277014717** [roxas75/rxTools#337]
Now new3ds use rxtools enumNAND support 10.3? or still 9.5

**Comment by Syphurith** [comment]
@ai277014717 If you can't have keys/ways to emulate booting process, you can't properly boot to the emuNAND. And, yeah the EmuNAND support for N3DS is still 9.5 ATM.

**Comment by ai277014717** [comment]
I see. Thank you.

**Comment by Syphurith** [comment]
@ai277014717 Thanks for understanding. It would come when it comes (orz) when possible.
