### ISSUE TITLE
Currently no way to download any of the nightly builds

### ISSUE THREAD

**Issue by sykhro** [roxas75/rxTools#342]
Dropbox has disabled the link because they generated too much traffic. 
I don't know if this has already been addressed, but at the moment there's no way to download a compiled version of recent builds

**Comment by mariogamer2** [comment]
https://github.com/mariogamer2/rxtools-prebuilt

I'll update it,but I can do it: Monday,Tuesday,Wednesday,Thursday

**Comment by sykhro** [comment]
I can compile this, but people are downgrading and a lot of them want to use rxTools. Point is, that both readme here and online tutorial have a link to the other build server.

**Comment by Tjessx** [comment]
I believe that there was someone who made a script that daily downloads and compiles the latest version of rxtools from this repo.

**Comment by PeggerWed** [comment]
Except since rxTools still isn't updated to newest libctru/DevKitARM, that script will error in the end with no compiled version left!

**Comment by mariogamer2** [comment]
Not real the version can be compiled,just clone by yoursefl CakeHax/CakeBrah and make heme.

**Comment by sykhro** [comment]
The end user is never even going to attempt building rxTools.
Builds have to be up again, somehow

**Comment by mariogamer2** [comment]
I'm a end user,don't know how to develop,but know building!!!

And I'm 15 years old :D

**Comment by sykhro** [comment]
>implying everyone knows how to build
This is not gonna help. Nice of you to set up a got with precompiled builds (and copyrighted files), but almost no one knows you did it. Forums are full of people struggling to get a recent build

**Comment by sykhro** [comment]
http://lavanoid.github.io/ is working again, so I guess this can be closed

**Comment by urherenow** [comment]
Nice background pic 😃

**Comment by mariogamer2** [comment]
Lavanoid's site is very unstable

I linked my prebuilt on GBAtemp

**Comment by urherenow** [comment]
Hope you didn't upload the latest. It's broken.

**Comment by mariogamer2** [comment]
What do I ahve to upload? latest commit work fine...

**Comment by sykhro** [comment]
Can't we just use something like box or mega instead of dropbox?

**Comment by mariogamer2** [comment]
yeah but mega is very copyrighted and lot od link was disabled....

Also, @lavanoid is working in creaing a special website:

https://github.com/lavanoid/lavanoid.github.io/issues/2#issuecomment-168898778

**Comment by urherenow** [comment]
@mariogamer after a build, just .zip the release folder and upload that. Or alternatively, zip up everything inside of the release folder, keeping the directory structure.

**Comment by lavanoid** [comment]
Fixed. Site is working, builds are on VPS, yadda yadda.

I just have to configure cron to check for updates, every so often.
