### ISSUE TITLE
Add new Autoboot option...

### ISSUE THREAD

**Issue by ApacheThunder** [roxas75/rxTools#343]
I don't know if it's a bug or not, but with auto boot enabled and using menuhax (specifically ctrbootmanger) to boot rxTools, holding/pressing L to boot to GUI to skip autoboot is difficult to do on time. The problem is it doesn't wait long enough or give you any message when to use the L button. I have tried holding the L button down while it boots and this causes the top screen to appear but nothing on the bottom screen. (though it did respond to the select button and shut down the 3DS, so it wasn't frozen?)

If I press L at exactly the right moment after ctrbootmanager finishes it's thing and right as rxTools pops up, then it works correctly. Perhaps it's a bit difficult to time correctly because the top screen image I set for menuhax is also the top screen image for rxTools. But I want them to be the same! :P

May I suggest the option of an additional settings in config to allow for setting a delay for autoboot? It will especially help us menuhax users who don't always want to boot straight into emunand. (or sysnand if it's set to do that)

**Comment by urherenow** [comment]
You can set a delay in ctrbootmanager and/or press L before (or at the same time) you select rxtools from the menu. I personally configure rxtools to force UI.

**Comment by ApacheThunder** [comment]
Ahh I see. I recall coming across that right after posting this. Sorry.
I'll go ahead and close this. :P
