### ISSUE TITLE
Remove PDF docs from current source. Copy Readme.md to release folder when building.

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#346]
The docs are super outdated. The lack of any proper instructions is compounding the fact that rxtools can't seem to handle machines recently downgraded from 10.3 (they get "cannot find emunand").

There is at least *some useful info in Readme.md so it's better than nothing in the short term.

Edit: unless @nastys has time to update the pdf files. Minus some new stuff being worked on, most of the really important changes are solid and probably won't change again any time soon. (such as what firmware files are needed, where to put them, and which link to use for spider.

**Comment by mariogamer2** [comment]
I'm agree about deleting PDF,but disagree with the fact of the downgrade.I know guy who downgraded and it's work.

**Comment by urherenow** [comment]
I'm dealing with no less than 3 people at the same time, who can't get it working. They all have a 10.3 downgrade in common.

**Comment by mariogamer2** [comment]
Maybe this is because this is not with the "official software".

Anyone have to wait for KTM.

**Comment by motezazer** [comment]
"Cannot find emuNAND" will appear if there is no emuNAND... (RxTools does
NOT create any emuNAND on the SD card)
It has no link with downgrade.

**Comment by mariogamer2** [comment]
I was pretty sur of this.

Since you told this,does this is possible to add a emuNAND creation?

**Comment by urherenow** [comment]
but that isn't the issue. These people have tried formatting emunand with the Gateway launcher and Emunand9 multiple times.

**Comment by urherenow** [comment]
Anyway, that's not the purpose of this issue, just a reason. The state of docs, and lack of the Readme that's already written in the release has made troubleshooting a huge headache.

**Comment by MelonGx** [comment]
I have the milnares's super large PDF on my harddisk. But its N3DS part is a little outdated.
Dunno about Google Docs since it's blocked by China government and I can't use VPN to watch either.

**Comment by MelonGx** [comment]
I have the milnares's super large PDF on my harddisk. But its N3DS part is a little outdated.
Dunno about Google Docs since it's blocked by China government and I can't use VPN to watch either.

**Comment by MelonGx** [comment]
I think we can use milnares's super large PDF instead of old ones.
BTW, is the Google Doc the latest milnares version? I can't watch it even I use VPN so I don't know. I only have an old PDF with N3DS installation outdated.

**Comment by Syphurith** [comment]
@urherenow Mind you please tell me how do you feel about the status of this issue? Is that solved?

**Comment by urherenow** [comment]
Oh, yea. @nastys already committed my pull request.
