### ISSUE TITLE
unicode chars when saving xors 

### ISSUE THREAD

**Issue by Desterly** [roxas75/rxTools#347]
Originally thought this was due to the TMIO drivers but a fresh pull from here results in the same issue.
Instead of a different issue in that thread, opening a new issue

Build environment:
Ubuntu 14.04
CakeBrah commit:  aca4aa7d3b3d2d195788c0b2555b307fbac63a7f
CakeHax commit: 6b8fca0b37a370a605f76b34b133da91a0b40f5e
devkitARM r45 (latest update sync)

Generating from a ncchinfo.bin file with 2 entries.

Processing only shows 1 file processed and saved to sdcard w/ this name:
〯〴〰㔲⸰湩桸敤潸摡

I'm assuming this is a build environment issue.  Anyone ran across this or can recommend commits/devkit revisions to build from?

**Comment by mariogamer2** [comment]
Latest Commit,latest ctrulib,latest devkit,and CakeHax CakeBrah maked by yoursefl.

**Comment by ApacheThunder** [comment]
Yeah you'll have to download and build Cakehax and CakeBrah compile them with make then moving them over to rxTools instead of using the ones that Github downloads along with rxTools. (assuming you're using the desktop program). I was able to compile it and have not had any issue getting it to work thus far.

**Comment by ApacheThunder** [comment]
Yeah you'll have to download Cakehax and CakeBrah and compile them with make then moving them over to rxTools instead of using the ones that Github downloads along with rxTools. (assuming you're using the desktop program). I was able to compile it and have not had any issue getting it to work thus far.

**Comment by mariogamer2** [comment]
Using 3DS

**Comment by Desterly** [comment]
Yes this is an o3ds.  

Just reinstalled devkitpro (r54)
pulled down Cakehax/CakeBrah and built, then merged and built rxTools with same result

Maybe i'll try downloading and building on windows.  not sure why that make a difference but worth a try.

**Comment by mariogamer2** [comment]
Maybe an error with ctrulib,because CakeHax have not 1.1.0,he have 1.0.0

**Comment by Desterly** [comment]
I wondered that as well.   I might try downgrading ctrulib and see if that makes a different.  It's odd because everything else seems to be working.

**Comment by Desterly** [comment]
Actually I figured it out.. it's not my buildbox it's the unicode commit

5fa3aeeffa27ae55e79e4050a4c626bef2b8650f

reverting that out corrects the problems.  

I'm guessing I'm one of the few people who built and tried to dump xors

**Comment by urherenow** [comment]
Wonder if it is causing issues with the downgraded 10.3 consoles not finding emunand...

**Comment by Desterly** [comment]
yeah... i forked the repo and pushed all my commits so anyone is welcome to try it.
That has:
    the new SDCard drivers
    Unicode reverted/disabled

Prebuilt here: https://www.dropbox.com/s/5wng13zpz1ccrzx/release.zip?dl=0

**Comment by mxalbert1996** [comment]
Found the problem. I suppose this is because the type of the `filename` field in the `Ncchinfo` struct (in `padgen.h`) has changed from `char` to `wchar_t` and is no more compatible with ncchinfo.bin. I reverted it back to `char` and it worked.

**Comment by Desterly** [comment]
Yeah that works too.  It'll need to be done to the extractors as well.  Pretty much anyplace filenames are specified.

**Comment by urherenow** [comment]
Why was this closed? I didn't see a pull request that fixes it...?

**Comment by Desterly** [comment]
ught.. i need to stop looking at github on my phone. my fault

**Comment by urherenow** [comment]
Yea... Some people are reporting the last update data suite fails, even though the Dec 5 works ( so they MUST already be using the correct firm files...)
