### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Shadow322** [roxas75/rxTools#353]
make[2]: *** [khaxinit.o] Error 1
make[1]: *** [build] Error 2
make[1]: Leaving directory `/c/rxTools_BuildKitWindows/rxTools/CakeBrah'
make: *** [all-target-brahma] Error 2

I don't know how to fix

**Comment by hartmannaf** [comment]
Git submodule update inside of the cakebrah folder should help.

**Comment by urherenow** [comment]
Do a fresh clone of rxtools. The submodules are already updated. You need to install the latest devkitpro (or at least install the latest ctrulib.

close the issue. It builds perfectly.

**Comment by Shadow322** [comment]
All working now ;)
