### ISSUE TITLE
Error installing datasuit 

### ISSUE THREAD

**Issue by carlitos92jose** [roxas75/rxTools#354]
Im having problem installing data suit en the recents version on rxtool, always get to the second square and pop the error message press any key

**Comment by hartmannaf** [comment]
could be usefull, if you give us the 3ds type(o3DS/2DS/n3DS) and the rxtools version you use.

**Comment by carlitos92jose** [comment]
sorry forgot to post that, im using a o3ds with sysnand 9.2 and emunand 10.3 with latest nightly bbdaaea the previous release also give that error, the version that i'm using now and install the data suite properly is the a08cfdd

**Comment by mariogamer2** [comment]
Me too with 2ds 6.0 and latest rxTools.Before latest,it work.

**Comment by AlbertoSONIC** [comment]
I tried latest rxTools on both n3ds and o3ds and data installation worked flawlessy...

**Comment by carlitos92jose** [comment]
now I tried the cc4000b and still the same problem, what are the steps that you do to install it? I did not need the firmware.bin right? just the firm folder that is generated with the cdn_firm.py?

**Comment by Shadow322** [comment]
The python.py script is for o3ds only for n3ds get the firmware file name
it 0004013820000002.bin and place it in the rxTools\firm folder and the
MD5: B99ADF0ADB279712367C06EB83BA9AE6

**Comment by urherenow** [comment]
Check the file sizes that get downloaded with the .py. Some ISP's are blocking the Native_firm file for some stupid reason (in my case, native_firm ends up 4K and is actually an html file telling me it was blocked)
It goes without saying (I hope) that you need some free space on your card as well, and the lock tab didn't slip, making your card read only...

**Comment by carlitos92jose** [comment]
I checked and all is fine, remember that the problem that I'm having is with the latest rxtool. Im using this a08cfdd revision and the datasuite installed fine, the problem is with the last one. I tried bbdaaea and cc4000b and failed to install datasuite but a08cfdd works fine.

**Comment by mxalbert1996** [comment]
Some people who were using exactly the same rxTools folder I shared with them also reported this problem. Their datasuit installation failed at the second square every time but they could boot emunand. Really weird.

**Comment by Shadow322** [comment]
O3DS?

**Comment by carlitos92jose** [comment]
yes thats exactly what's happening to me, the installation failed at the second square

**Comment by urherenow** [comment]
I just used the latest build. Still have no such issue.

**Comment by mxalbert1996** [comment]
So can we say this problem only happens when using o3ds downgraded from 10.3 to 9.2?

**Comment by Shadow322** [comment]
No I downgraded my o3ds xl from 10.3 and has never had this issue

**Comment by carlitos92jose** [comment]
this is so weird why for some people works and others don't like in my case. And I did everything right and I'm using an older revision without problem.

**Comment by carlitos92jose** [comment]
just tried the new 647b341 revision and that freeze on the second square of installing thats different from the other that I tested

**Comment by AlbertoSONIC** [comment]
Just tried the very latest commit, on o3ds 9.2, and worked perfectly...

**Comment by carlitos92jose** [comment]
I have a question, do you'r emunand is made with gateway or emunand9?

**Comment by AlbertoSONIC** [comment]
Gateway, but it doesn't affect the data installation. There must be something wrong with your firmware files (the ones inside rxTools/firm)...

**Comment by carlitos92jose** [comment]
ok so I installed the a08cfdd revision and the datasuit installed perfectly, then I tried the latest commit 647b341 and use the firm that was created with the a08cfdd and the same happened, it froze at the second square so I'm pretty sure the firm folder is fine. Could you send me your latest build just to test if something is wrong with my build? mine compiled fine but just in case

**Comment by Desterly** [comment]
@carlitos92jose try this build: https://www.dropbox.com/s/5wng13zpz1ccrzx/release.zip?dl=0

it's a few days old but it has all of the unicode commits reverted.   there was problems in a few other areas but if that build works, the unicode probably needs to be reverted here too

**Comment by carlitos92jose** [comment]
Ok i tried this version and the installation was succesful! no error on installing the datasuite and it booted fine to the emunand

**Comment by Scrxtchy** [comment]
@Shadow322 
Thanks
![](https://jii.moe/V1pl8g1ux.png)

**Comment by Desterly** [comment]
This is another unicode problem.   I spent some time looking at it tonight but didn't track down the correct fix (short of totally reverting unicode).

One thing that I will say is that if _STRF_ENCODE is changed from 1 to 3, files are correctly named (not having the bad file names as before) but even w/ this it still hangs after 2 blips for me.  

Totally reverting out unicode and it installs as i'd expect

**Comment by urherenow** [comment]
On a USA console, I'm not having data suite issues with the latest build. And @173210 uses a Japanese one. Then again, I never understood the need to use Unicode on any file operations whatsoever. Are there any Unicode files or headers in JP games or firmware files?

**Comment by 173210** [comment]
#359 may fix this issue.

@urherenow
This commit should improve file manager (although @AlbertoSONIC didn't use lfname LOL. @AlbertoSONIC, read the document of libraries before you use them! FAT is really complicated.)
But my real intention is to remove character conversion. Stupidly, it had converted UTF-16 -> UTF-8 -> UTF-16. The conversion should be removed before it gets harder by adding more codes.

**Comment by Desterly** [comment]
@173210 #359 does indeed seem to resolve this.  dataset is installing correctly for me now.
Only thing I saw was the json config file isn't being created during installation but it does create it when a setting is changed.

**Comment by Shadow322** [comment]
This pull pushed yet to git?

**Comment by urherenow** [comment]
It is now.@carlitos92jose please try the latest. If it fixes your issue, please say so and close this issue.

**Comment by carlitos92jose** [comment]
Just tested the latest commit 3c82cd8 and the datasuit installed fine!!! the problem is finally fixed. Thanks for your hard work.
