### ISSUE TITLE
stuck compiling???

### ISSUE THREAD

**Issue by Shadow322** [roxas75/rxTools#356]
It's been sitting on "CONVERT build/font.bin" for about 45 mins

**Comment by urherenow** [comment]
Hit enter? Or CTL+C? Shouldn't be stuck... have you built it yourself before? If not, are you sure you have imagemagick installed and in your system path?

**Comment by Shadow322** [comment]
I compiled comment bbdaaea fine yesterday

**Comment by Shadow322** [comment]
Idk works now

**Comment by urherenow** [comment]
Ok. If you ever get stuck during a build, it's best just to terminate it, make clean, then make release again.

**Comment by urherenow** [comment]
Oh, but if it's ok now, please close the issue :)

**Comment by urherenow** [comment]
Annnnd... It was already closed. My work internet sucks and I'm on my phone. Sorry :P
