### ISSUE TITLE
#360  broke Pasta mode

### ISSUE THREAD

**Issue by urherenow** [roxas75/rxTools#361]
@173210 @AlbertoSONIC Not only that, but on second boot (obviously after data installation suite was done from the first boot), I get the warning screen about the key x and I'm on 9.2 sysnand. #360

**Comment by urherenow** [comment]
It also seems that the mSD is read only when using the mSD management (wireless thingy).

**Comment by Syphurith** [comment]
*@urherenow Tokyo? Do you live there? You might find 173210 since he is Japanese* Warning about KeyX? Might cause the KeyX isn't needed on 7.x+ sysNand so .. Or just not clean code enough..

**Comment by urherenow** [comment]
He lives farther north. It's an IO issue because it didn't happen until that last commit.
