### ISSUE TITLE
[REQUEST] Update FBI

### ISSUE THREAD

**Issue by mariogamer2** [roxas75/rxTools#374]
There are a lot of version between the fbi_injection of rxTools and FBI: https://github.com/Steveice10/FBI ,may it can be updated?

This is not obligatory (lot of version to create) but it will be good.

**Comment by Zetchzie** [comment]
Cant you just dl fbi and place the updated version in the fbi injecters place and install that way you know what im getting at.

**Comment by piratesephiroth** [comment]
wel that's not too difficult.
I might do it.

**Comment by mariogamer2** [comment]
Personally,I can't because rxTools won't inject my backup of health and security.

**Comment by piratesephiroth** [comment]
yeah I've made some injectable DevMenu files before

**Comment by Syphurith** [comment]
@d0k3 and I have made the injectable files maker, Refer this page: [Gbatemp](https://gbatemp.net/threads/release-inject-any-app-into-health-safety-o3ds-n3ds-cfw-only.402236/). And Decrypt9 can inject things into N3DS, which Rx could not now. So i recommend users to use d0k3/Decrypt9 for this deed.

**Comment by piratesephiroth** [comment]
yeah, why can't rxTools inject FBI/DevMenu into N3DS's NAND?

**Comment by urherenow** [comment]
This whole injection into H&S is pointless. As long as browserhax is an option, the .cia can be installed normally as long as it's done before fully upgrading emunand.

**Comment by piratesephiroth** [comment]
I like the feature only to inject DevMenu directly, because FBI sucks.
What a miserable interface...

**Comment by sykhro** [comment]
DevMenu injection is not likely to happen since DevMenu is copyrighted software (and needs to be installed to the NAND partition, not on the SD. Or at least,, the latest version requires this)

**Comment by piratesephiroth** [comment]
Yeah I know we're only allowed to pack homebrew.
It's just that rxTools actually doesn't care about the executable contents. As long as the hashes and sizes are OK, anything will be injected.

**Comment by mariogamer2** [comment]
Ok I can do it
