### ISSUE TITLE
New rxTools installation stucks at "Installation successful"

### ISSUE THREAD

**Issue by ofry** [roxas75/rxTools#376]
Problem with nightly build rxTools_2016-01-28_15.54-4876174
I have O3DS XL, firmware 4.3, formatted SD card.

1) I put contents of /release folder in root of SD card
2) launched cdn_firm.py and put /firm folder in root of SD card.
3) Launched rxTools via browser page https://dukesrg.github.io/?rxTools/sys/code.bin

Next I got freeze at "Installation successful. Press any key to continue" screen :(

**Comment by Shadow322** [comment]
Put the "firm" folder under /rxTools/ so its /rxTools/firm

**Comment by urherenow** [comment]
And delete rxtools/data

**Comment by ofry** [comment]
Thanks.

**Comment by urherenow** [comment]
If you're sorted, please close the issue.
