### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by musdem** [roxas75/rxTools#380]
When I try to compile on the latest commit (4876174 currently) I get [this](http://pastebin.com/CKkLpLjP) error. I have been looking around and I have not found any solutions as to how to fix this so I assume there is an issue with the code.

**Comment by ApacheThunder** [comment]
I just updated the build...And it compiles fine. What ever your problem is, is not related to the last commit.

**Comment by mariogamer2** [comment]
This compile fine on linux.

Do you have ctrulib/devkitARM up-to date?

**Comment by Desterly** [comment]
make sure your subrepositories are sync'd.  my guess is the CakeBrah project didn't get initialized and pulled down

**Comment by musdem** [comment]
All my subrepos are synced @Desterly . I discovered that this compiles on my laptop dispite having the exact same distro as my desktop @mariogamer2 that being said my laptop and desktop has devkitARM but not ctrulib so I'm not sure what the difference is, I'll probably find a way to compare installed packages to see what is missing.
