### ISSUE TITLE
9.6+ N3DS

### ISSUE THREAD

**Issue by PokeAcer549** [roxas75/rxTools#383]
Will 9.6+ emuNAND ever wrok?

---PLEASE NO KEYS, THANKS---

**Comment by motezazer** [comment]
We already had that key anyway.

**Comment by mariogamer2** [comment]
Key!!! Key!!! Key!!! XD

**Comment by Zetchzie** [comment]
why isn't this already a thing? what's keeping this if you would care to educate me.

**Comment by mariogamer2** [comment]
There are two choice:

1.Support 9.6 FIRM with very unstable emuNAND
2.Support 10.4 FIRM with very good emuNAND

**Comment by motezazer** [comment]
9.6 FIRM is not *very* unstable, but it's not as stable as the second option.
And the RxTools users choosed in a twitter poll the option (it's not completly arbitrary)

**Comment by mariogamer2** [comment]
Yeah

**Comment by motezazer** [comment]
It's out now.

**Comment by Zetchzie** [comment]
Ok so how do I get those new bins? can i dump them from a n3ds Since they are nonexistent at the moment ill stick to Reinand.
