### ISSUE TITLE
error compiling  latest nightly

### ISSUE THREAD

**Issue by carlitos92jose** [roxas75/rxTools#385]
Im trying to compile the latest nightly and now, Im having this error: cp: cannot stat 'QuickStartGuide.pdf: no such file or directory make:  [release-doc] Error 1. Something like that

**Comment by urherenow** [comment]
line 	86 -> @cp README.md **doc/**QuickStartGuide.pdf releas

**Comment by urherenow** [comment]
fixed. Close the issue please.

**Comment by mariogamer2** [comment]
Thank @urherenow I was thinking thats but too late :D
