### ISSUE TITLE
how to fix????

### ISSUE THREAD

**Issue by Shadow322** [roxas75/rxTools#386]
cp: cannot stat `QuickStartGuide.pdf': No such file or directory
make: *** [release-doc] Error 1

**Comment by urherenow** [comment]
There was already an issue opened.

line 86 -> @cp README.md **doc/**QuickStartGuide.pdf

**Comment by urherenow** [comment]
fixed. Close the issue please.

**Comment by Shadow322** [comment]
I have confirmed this issue is fixed so I will close this issue now :)
