### ISSUE TITLE
Missing version string in Settings

### ISSUE THREAD

**Issue by darxmorph** [roxas75/rxTools#390]
My O3DS is not showing 'RX-E' / 'RX3D' at the beginning of the version number in emunand.

I think it was after returning to settings from 'Nintendo Network ID Settings'.

I've also rebooted the 3DS and it's still like that.

Before you ask, YES, I'M ON EMUNAND. I'M SURE.

INFO:
System: O3DS XL (E)
rxTools: 3.0 (from updated CFW KIT)
emuNAND: 10.5
sysNAND: 9.2

**Comment by darxmorph** [comment]
IDK why, but RX-E is back. However, going back to System Settings from NNID settings, will make RX-E disappear, while still being in emunand.

**Comment by deadair3210** [comment]
I am having the same issue on 10.5 emuNAND. Sparodicly the RX-E will disappear only to reappear the next time I look. I know I am on emuNAND as well, as I have themed sysNAND and emuNAND differently to make it easier to tell which I am in

**Comment by Committee** [comment]
I think it was after returning to settings from 'Nintendo Network ID Settings'.

going back to System Settings from NNID settings, will make RX-E disappear, while still being in emunand.

Doing these two will make you go into Sysnand if you are in Emunand.

You can confirm this by setting a different brightness level for Sysnand and Emunand.

**Comment by darxmorph** [comment]
AFAIK, you return to Sysnand when quitting System Settings. Quitting nnid settings will still display ver. 10.5 which can only be Emunand.

**Comment by urherenow** [comment]
So what? It's not like you can get into a dangerous situation from this point. You're going to get kicked back to sydnand no matter what.

This issue is pointless.

**Comment by darxmorph** [comment]
I mentioned that specific situation 'cause it's the only reproductive situation I found.
The thing is: sometimes, when going into settings, 'RX-E' is missing. Sadly I can't provide more info.
So yeah, not a major issue.

**Comment by AlbertoSONIC** [comment]
Are you using the very latest build?

**Comment by darxmorph** [comment]
I'll install latest nightly and let you know if it happens again.

**Comment by sykhro** [comment]
The same issue being reported over and over, the string sometimes gets replaced in other places than mset
