### ISSUE TITLE
Injection Failed "Can't find H&S data"

### ISSUE THREAD

**Issue by ElvisCortijo** [roxas75/rxTools#395]
Old 3ds With 6.3.0.12U Firnmware, rxtools 3
When Charge Instalation Data Suite, i got INSTALLATION FAILED message
When Try Check TMD Version in EMUNAND, got Message:
Opening SecureInfo_A: OK!
Region: USA
Press A to Exit.
I can't Got the TMD Version number, if i try injection:
Error: couldn't find HT&S data

**Comment by piratesephiroth** [comment]
When this happens you can only use Decrypt9 to dump your system settings and and inject FBI / DevMenu

**Comment by mariogamer2** [comment]
@piratesephiroth Why? I personnally don't have the problem,but just by curiosity :D

**Comment by piratesephiroth** [comment]
Sometimes rxTools can't read H&S's version in the TMD. I have no idea why (maybe it has a weird unknown version?).

Is thoses cases you need to use Decrypt9 and [this injector] (https://github.com/d0k3/Universal-Inject-Generator) to dump H&S, convert and inject other app (I recommend DevMenu)

**Comment by ElvisCortijo** [comment]
Thanks @piratesephiroth, i try install Decrypt9 and follow your Idea.

**Comment by MelonGx** [comment]
Gateway DGed 4.X are frankenfirmwares.
They make FBI injection unable to recognize correct H&S.
But since TC's is not GWDG 4.X, it should be a new issue.

**Comment by piratesephiroth** [comment]
Yeah I've seen it happening a few times. It's not only caused by Gateway.
