### ISSUE TITLE
[ImageMagick] Huge font.bin when using latest ImageMagick

### ISSUE THREAD

**Issue by TuxSH** [roxas75/rxTools#397]
When trying to build rxTools, ImageMagick never stops generating font.bin (stopped it at 40GB). Its contents are ``AA AA (zeroes)``.

Using Win7 x64, ImageMagick-6.9.3-3-Q16-x64-dll.exe.

**Comment by Mister-Arkse** [comment]
Same here, switched to ImageMagick-6.9.2-10-Q16-x64-dll.exe and problem solved :)

**Comment by TuxSH** [comment]
Could you give a link?

**Comment by Mister-Arkse** [comment]
ImageMagick 6.9.2-10 x86 & x64 for Windows :

https://www.dropbox.com/sh/spsjhywnvppgfnb/AACOcEaZYejnjd3bEtNXPBJWa?dl=0

**Comment by mariogamer2** [comment]
It's the same on linux or not?

I'll test this soon.

**Comment by dukesrg** [comment]
Compatibility with the latest 6.9.3-3 should be fixed with #416

**Comment by Mister-Arkse** [comment]
No problem building rxTools with #416 but rxTools screen is messed up now on my N3DS :

http://imgur.com/erQ9gwB

(Windows 7 x64, ImageMagick 6.9.3-3-Q16-x64)

**Comment by dukesrg** [comment]
Theme generation was affected with 9.3.3 too, will try to fix tonight

**Comment by dukesrg** [comment]
Reported issue to ImageMagick
https://github.com/ImageMagick/ImageMagick/issues/132
@Mister-Arkse Please check with the latest ImageMagick beta
http://www.imagemagick.org/download/beta/ImageMagick-6.9.3-5~beta20160217-Q16-x64-dll.exe

**Comment by dukesrg** [comment]
Ok, should work fine with the latest 6.9.3-5 release, please check @Mister-Arkse

**Comment by Mister-Arkse** [comment]
Working fine now with 6.9.3-5 release, nice work :)

**Comment by dukesrg** [comment]
@TuxSH please check it too and close the issue

**Comment by dukesrg** [comment]
@AlbertoSONIC I suppose this once can be closed

**Comment by TuxSH** [comment]
Sorry for being late :/
It's working fine now.
