### ISSUE TITLE
Today's new rxTools has data installation freezing on both O/N3DS - seems that TWL_FIRM decrypting failed

### ISSUE THREAD

**Issue by MelonGx** [roxas75/rxTools#398]
On N3DS, it freezes after 0/3 square filled.
If I force rebooting N3DS, it works fine.
But when I take a look on /rxTools/data, only a 972KB 0004013820000002.bin (NATIVE_FIRM) exists.

On O3DS, it freezes after 3/5 square filled.
If I force rebooting O3DS, it works fine.
But when I take a look on /rxTools/data, there are three files:
- 940KB 0004013800000002.bin (NATIVE_FIRM)
- 868KB 0004013800000202.bin (AGB_FIRM)
- 0KB 0004013800000102.bin (TWL_FIRM)
It seems that this version has an error on decrypting TWL_FIRM.
To confirm that, I try running my Dragon Quest 9 DS cart on it. It blackscreens.
That means it does have an error on decrypting TWL_FIRM.

**Comment by MelonGx** [comment]
BTW, DS cart on rxTools emuNAND
- Always available on O3DS + 9.X SysNAND, except today's new rxTools
- Always available on N3DS + ReiNAND FW used rxTools

**Comment by MelonGx** [comment]
BTW, DS cart on rxTools emuNAND
- Always available on O3DS + 9.X SysNAND, except today's new rxTools
- Always available on N3DS + ReiNAND FW used rxTools

**Comment by urherenow** [comment]
I have no such issue on N3ds. I have had several freezes with O3DS though (installation data suite).

**Comment by piratesephiroth** [comment]
yeah it took a lot of tries here (O3DS) until it froze on the third square of the installation.

I rebooted and got into emunand fine, but data/0004013800000102.bin  is a 0KB file

**Comment by piratesephiroth** [comment]
BTW If I select DECRYPT TITLE KEYS it just freezes.

This version is pretty broken, hue

**Comment by urherenow** [comment]
You'll have to delete the /data folder and keep trying to fix the 0kb file. The lack of json has been normal for a long while now. You will only get it if you change something in the settings (I always set "force ui" because it makes my success rate pretty much 100%, limited only by the success rate of menuhax+ctrbootmanager).

**Comment by blazevx** [comment]
I tried the 8c30bd6 build and can confirm that I'm unable to get past the Data Installation with none of the boxes getting filled with multiple failed attempts to get it working by deleting the /data file and repeating the process.

Had to revert to the c304489 build since it was the last one that is fully functional.

**Comment by urherenow** [comment]
apparently this also freezes when trying decrypt functions as well. I don't understand it. The latest commit (before the readme) seemed to only involve ktr changes, but CTR is really messed up.

**Comment by AlbertoSONIC** [comment]
Tried data installation two times with latest build on my n3ds and it works fine. Now I'll try o3ds

**Comment by AlbertoSONIC** [comment]
Tried also on o3ds, two times, and it always worked fine. Also twl works!

**Comment by piratesephiroth** [comment]
restoring line 110 of rxtools/source/features/firm.c,

aes_decrypt(hdr->ext.s.keyX_0x16, key, NULL, 1, AES_ECB_DECRYPT_MODE);

seems to fix the installation issues on the O3DS.
(I have no idea of what side effects it will have though)

**Comment by blazevx** [comment]
Everything works again as of the d2ee1bc build that was released a little while ago.

**Comment by urherenow** [comment]
This is fixed. Please close it.
