### ISSUE TITLE
RE: current method (readme.md)

### ISSUE THREAD

**Issue by RandomIntermition** [roxas75/rxTools#402]
Quote:
(abridged)

Old 3DS or 2DS, Python 2.7 
run /Tools/o3ds_cdn_firm.py. 3 files into a folder named /firm. 

New 3DS, Python 2.7
run /Tools/n3ds_cdn_firm.py. 1 file into a folder named /firm
also need
key_0x16.bin (N3DS arm9bin decryption, 9.6+ keyX)
key_0x1B.bin (N3DS 9.6 NCCH keyX) on the root of your SD card.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
QUESTION:

can somebody working in this area let me know if this method (specifically the n3ds 1firm 2bin setup)... is going to change or stay the same after 3.0 final release.
i.e. are the 2 key '.bins' just a temp fix on n3ds, until they're added into the main rxtools?

just need a clarification on that please thanks.

additionally:

if someone could post the MD5 of key.bins.
i'm o3ds, so would be quicker/easier for someone to post them, than for me to find and download something i don't actually need, just need the MD5's for referencing. thanks.

**Comment by urherenow** [comment]
Already posted @ gbatemp.

**Comment by RandomIntermition** [comment]
i presume you're talking about the MD5's. are they on main/support/tutorial? 

ALSO... still need someone to tell me if the 2 n3ds bins will still be needed when using the final 3.0 build. thanks.

**Comment by RandomIntermition** [comment]
found solution elsewhere,

**Comment by urherenow** [comment]
Main: page 872. Also in Rei's pastebin.

Glad to see you're sorted. Just adding the info for future reference.
