### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by RandomIntermition** [roxas75/rxTools#407]
is anybody still working on a 3.0 full guide (currently titled "rxTools.pdf")
if so what stage are you at?

i don't want to do any work on it if someone else is midway through working on it aswell.
thanks
ref.
#56 #273

**Comment by urherenow** [comment]
If anyone, I think it would be @Nastys

**Comment by RandomIntermition** [comment]
checked @nastys rxtools fork and there aren't any recent commits so not sure.

**Comment by RandomIntermition** [comment]
closed, pushing ahead, will send a merge with WIP once it gets underway so people know what stage it's at.
(it's not currently included in any release so won't cause any issues.)
