### ISSUE TITLE
rxTools menu's language fonts have been messed up on e2c1e58

### ISSUE THREAD

**Issue by MelonGx** [roxas75/rxTools#412]
As topic.

**Comment by urherenow** [comment]
Might be a problem withImageMagick on the lavanoid builds. Roll your own; I have no such issues.

**Comment by Shadow322** [comment]
I second that build your own

**Comment by MelonGx** [comment]
This problem happened on my own build.
So what's the problem?
Need an Image Magick upgrade?

**Comment by MelonGx** [comment]
Upgrading ImageMagick 6.9.3.1 to 6.9.3.3

**Comment by MelonGx** [comment]
Oh, what the fuck, it's the same issue as #397 - the huge font.bin!

**Comment by mariogamer2** [comment]
Does this happens on linux?

**Comment by MelonGx** [comment]
Since Dropbox is banned by China Government, I can't DL 6.9.2-10.
So I lay this issue down.

**Comment by MelonGx** [comment]
I have Windows only so I don't know.

**Comment by MelonGx** [comment]
Tried 6.9.1-10.
It can't generate anything except code.bin and another huge font.bin (3.13GB) by "make release".
BTW, the "git clone"-ed source code size (3GB) is weird either.

**Comment by urherenow** [comment]
You need version 6.9.1 or 6.9.2. 6.9.2 is posted on gbatemp. Search for any post by me and the link is in the compiling rxtools thread (in my sig)

**Comment by dukesrg** [comment]
Compatibility with the latest 6.9.3-3 should be fixed with #416

**Comment by MelonGx** [comment]
Fixed by #416. Closing issue.
