### ISSUE TITLE
Add emuNAND support?

### ISSUE THREAD

**Issue by PokeAcer549** [roxas75/rxTools#426]
Using emuNAND9 (https://gbatemp.net/threads/release-emunand9tool-open-source-emunand-formatter-manager.405921/) we could perhaps implement emuNAND setup into rxTools, considering it is GPL v2.

**Comment by dukesrg** [comment]
+1
@AlbertoSONIC merge with #392 please

**Comment by AlbertoSONIC** [comment]
It's already planned ;)

**Comment by mariogamer2** [comment]
Yeahh!!!!!!
