### ISSUE TITLE
Clicking "Gen Fat16 Xorpads" freezes on the 3.0 Beta 2 release

### ISSUE THREAD

**Issue by vgf89** [roxas75/rxTools#427]
I'm on an o3DS. System firmware version is 4.5 (downgraded from a previous 9.2 iirc).

Clicking the Gen Fat16 Xorpads option results in an immediate freeze. Nothing changes on screen, it just stops accepting input.

I was able to get my fat16 xorpad using Relys/3DS_Multi_Decryptor, but that's pretty roundabout since I had to switch to a different MSET ROP.

**Comment by mariogamer2** [comment]
Same thing on 2ds 6.0.0,no downgrade or anything else...

**Comment by MelonGx** [comment]
Same on Feb.15 (8d9e02a).
Need to fix it.

**Comment by Shadow322** [comment]
Does it happen on latest nightly build of RxTools?

**Comment by MelonGx** [comment]
It still occured on latest commit.

**Comment by MelonGx** [comment]
Seems that devs have no time to pay attention to this because they're fighting for arm9loaderhax support.....
