### ISSUE TITLE
[REQUEST] can we change...

### ISSUE THREAD

**Issue by RandomIntermition** [roxas75/rxTools#428]
can we change the wording a bit in settings?

the recently added commit number is a good idea, but i think it would make more sense for it to say:

Build: r7d63v4js
-or-
Build No. ek8wk54sn4

rather than just saying 'git', which doesn't really give an understanding of what the number is on its own. just a small change that someone could make, if people agree?

i haven't worked on the gui myself so don't know where that specific word is recorded.

**Comment by mariogamer2** [comment]
Think I know,but I don't know by what to change these world...

**Comment by RandomIntermition** [comment]
Solved :)
