### ISSUE TITLE
Can't Inject FBI correctly when multiple version of H&S versions exist

### ISSUE THREAD

**Issue by vgf89** [roxas75/rxTools#429]
On FW 4.5 (which was downgraded from 9.2 at an earlier date) it appears I have 2 H&S versions, v1026 AND v2051 in the same folder on my sysNAND. This old 4.5 firmware just launches the older H&S, but I can't overwrite that one through rxTools' FBI injection since it reports "Wrong TMD version!" due to the existence of the newer H&S version alongside the old one.

It needs to be able to overwrite any H&S that happens to exist on the system.

**Comment by urherenow** [comment]
No it doesn't. It needs to work on any firmware that isn't broken. If you have a Franken-Firmware, then fix it. Delete H&S with FBI or something, then reinstall it from a firmware pack.

Or use decrypt9 to get the job done.

**Comment by vgf89** [comment]
I suppose. It's not like it's a hard thing to fix though, and it's pretty common considering how many people (including myself) had downgraded back when Gateway released the tool for that.

Would it be possible to warn the user if they have multiple H&S files at least?

**Comment by vgf89** [comment]
I suppose. It's not like it's a hard thing to fix though, and it's pretty common considering how many people (including myself) had downgraded back when Gateway released the tool for that.

Would it be possible to warn the user if they have multiple H&S files at least?

**Comment by mariogamer2** [comment]
Why do you reopened? What is the problem?

**Comment by vgf89** [comment]
No, I closed it on accident (buttons for edit and close are pretty close
when viewing the desktop site on mobile)

**Comment by MelonGx** [comment]
GW DG 4.X are frankenfirmwares.
They are confirmed messing up FBI injection's TMD judgment.
FBI injection is not intelligent enough to judge frankenfirmware's TMD correctly.
So you have to manually inject it, or use GW to install Sysupdater/FBI directly to SysNAND.
