### ISSUE TITLE
[Request] Support for FW 2.1 on emuNAND

### ISSUE THREAD

**Issue by artur3004** [roxas75/rxTools#431]
As we all know to dump otp for arm9loaderhax wen need to be on fw 2.1. But it's risky for anyone who don't has a hardmod. If a cfw could boot a downgraded emunand to fw 2.1, no hardmod would be needed? Am I wrong?

**Comment by motezazer** [comment]
sysNAND has to be on 2.1, else OTP would have been locked by whatevermore-than-2.2 your sysNAND version is.

**Comment by hartmannaf** [comment]
It would not allow us to get te otp region, but it could help to check if the downgrade worked correctly, especialy if its also using the 2.1 or the emunand firm.

**Comment by urherenow** [comment]
Running in emunand is NOT an indicator that it won't brick your sysnand. NATIVE_FIRM is never loaded from the emunand, it is loaded from a firmware.bin file.

Go ahead and try updating a 4.x emunand to 7.x or above (NOT the latest through system settings, but with a cart or BBM or something). See that the emunand still works. NOW, flash it to sysnand... Usually, you will be bricked.

**Comment by AlbertoSONIC** [comment]
"sysNAND has to be on 2.1, else OTP would have been locked by whatever-more-than-2.2 your sysNAND version is."
This ^

I guess we can close this issue ;)
