### ISSUE TITLE
[REVIEW] rxTools Manual, (see attached)

### ISSUE THREAD

**Issue by RandomIntermition** [roxas75/rxTools#432]
please read the attached file and comment any errors or suggestions.

The file is a .pdf but is safe to open on your computer.
i decided to issue it this way, rather than having another pull request everyday.
once everybody's corrections/suggestions have been made i'll submit the final to 'docs'.

the current document is as the final will be, no other changes will be made unless needed.
(the title of the final version will be "rxTools_manual.pdf")

rev1:
first revision.
[rxTools_Manual_rev1.pdf](https://github.com/roxas75/rxTools)

rev2:
MSET & firmware info changed.
[rxTools_Manual_rev2.pdf](https://github.com/roxas75/rxTools)

rev3:
partial screens change only.
[rxTools_Manual_rev3.pdf](https://github.com/roxas75/rxTools)

**Comment by MelonGx** [comment]
For 3b-Launching via Browser, it is tested that -2 to -6 browser entrypoints are also unsupported.

**Comment by RandomIntermition** [comment]
What do you mean by "-2 to -6"? Do you mean browser versions?

**Comment by RandomIntermition** [comment]
what do you mean by "-2 to -6 browser entry points" are you talking about the browser version/firmware version? that doesn't make sense to me, maybe i'm reading it wrong.

**Comment by MelonGx** [comment]
There are some strange firmwares exist, such as #436.
rxTools's browser entrypoint (=CakeHax) has bad support about it.
They cannot be properly booted.
I suggest you adding this information to the manual to prevent noobs repeating asking about this.

**Comment by RandomIntermition** [comment]
rev2:
[rxTools_Manual_rev2.pdf](https://github.com/roxas75/rxTools/files/147314/rxTools_Manual_rev2.pdf)

**Comment by MelonGx** [comment]
Many thanks :P

**Comment by urherenow** [comment]
The commands for setting the path for devkit arm... Windows users REALLY want/need to place it first, then ;%path%. Devkit pro throws up if anything along the path has a space. Sometimes it doesn't like parentheses either (Program Files (x86)).

**Comment by RandomIntermition** [comment]
if the directory is properly set up (no spaces, no parentheses), as directories should be, then the order of %path% then additions or additions then %path% shouldn't matter at all or make any difference.

i assume you're talking about:
make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)

which is actually already mentioned in the notes at the end of the building from source section.

**Comment by RandomIntermition** [comment]
rev3:
partial screens change only.
[rxTools_Manual_rev3.pdf](https://github.com/roxas75/rxTools/files/149582/rxTools_Manual_rev3.pdf)

**Comment by RandomIntermition** [comment]
[CANCELLED] no longer of any use as 'pasta team' are taking an axe to rxtools removing most of its functions.

**Comment by urherenow** [comment]
Your comment about proper paths was stupid. It IS PROPER to have "Program Files (x86)" in the path of a 64bit Wondows. Correct info in one part of a manual does doe excuse incorrect instructions in another part.

But if you are cancelling your work, don't just comment [cancelled], actually close the issue.
