### ISSUE TITLE
n3ds glitch fix

### ISSUE THREAD

**Issue by Desterly** [roxas75/rxTools#441]
Looks like TIniVi and Cakes have implemented a fix for the messed up 3d on startup for n3ds.

https://github.com/mid-kid/CakesForeveryWan/commit/e810bd0b05c7a5b03ff38e1bbb214781cefffa1d

https://github.com/TiniVi/AHPCFW/commit/36efc113d2b28f5a5380c15458964b8a0d36f634

Looking over the code it seems pretty simple.   I'm assuming we'd implement this right before the execReboot in the rxMode() method in firm.c

**Comment by Zetchzie** [comment]
Hell yeah ^^

**Comment by MelonGx** [comment]
That means we don't need A9LH to fix that problem :P

**Comment by AlbertoSONIC** [comment]
Should be fixed in latest nightly
