### ISSUE TITLE
Latest build has no more devtools?

### ISSUE THREAD

**Issue by Committee** [roxas75/rxTools#451]
Hello,

Cannot seem to find the answer to this but how do you access the devtools in the latest commit (xorpad, fbi inject, etc)? Upon booting all I get is the 3 options (emunand, sysnand, pasta).

**Comment by Desterly** [comment]
The tools have been removed.   Decrypt9 handles all the functions these did and has been further developed since the ones in rxTools.

"rxTools" is also being renamed according to @AlbertoSONIC

**Comment by Committee** [comment]
https://github.com/archshift/Decrypt9

This Decrypt9?

**Comment by Desterly** [comment]
That's the "Stable" version, yes.   If you want an updated / development version use this one: https://github.com/d0k3/Decrypt9WIP

**Comment by Committee** [comment]
Thank you.
