### ISSUE TITLE
Fixing warnings

### ISSUE THREAD

**Issue by dukesrg** [roxas75/rxTools#46]
I'm trying to fix all insignificant warnings (i.e. which do not change the output) and hope to make a pull request tonight. However there are several warnings I can't fix or even which are the real typos or mistakes. I'll try to add it here, sorry for not using inline comments, but too huge commits hangs my browser when I'm at work :(

- fs.h:11:6: note: expected 'struct FIL *' but argument is of type 'struct FIL **'
(pointer error?)
- console.c:103:20: warning: comparison between pointer and integer
  if(findCursorLine < MAXLINES) point = &console[0];
(must be findCursorLine()?)
- ncch.c, all functions for 64-bit operation must use 'long long' but not just 'long' which is 32-bit only

upd: fixed all I could, will squash&pull request in the evening.

**Comment by Syphurith** [comment]
@dukesrg Thanks for your effort. To your questions:
* `fs.h`: it is actually expected as '```FIL*```' which is replaced from '```File*```'.
* `console.c`: yes it should be a function call instead.
* `ncch.c`: well you can include `common.h` to use those `u32`, or `u64`.

BTW, it is suggested to use a compiler to check those warnings generated. If some of them is not so *insignificant* you can try safely, such as `inproper pointer type` or `cast from interger to pointer`.

**Comment by dukesrg** [comment]
@Syphurith Yes, project was compiled with all fixed warnings and results binary compared with the orginal. I'll make a pul lrequest shortly.
As fot the above issues, I can't see why compiler expects FIL** instead of FIL*

**Comment by Syphurith** [comment]
@dukesrg Maybe that is just a typo when roxas added an extra '&' by mistake. I've seen such things.
when pull created, please tell them not to merge instantly so that it could be better reviewed.

**Comment by dukesrg** [comment]
Yes, I've found that error, really declared as a pointer and misused. Just created a branch with such errors fixed, it is better to separate those changes

**Comment by Syphurith** [comment]
@dukesrg Note: if you are using browser to access the code, you could just search for function names in the search box at the top of this page (or any other ones in this repo). Alternative to Grep-Like ones?

**Comment by dukesrg** [comment]
@Syphurith
I can browse code locally, but  can't commit it from work - ought to copy-paste and then squash at home :)

**Comment by dukesrg** [comment]
Fixed with 1b5627f34ff6e94ce82e616212f78582c2655120
