### ISSUE TITLE
Stuck with black screen

### ISSUE THREAD

**Issue by Reedkaan** [roxas75/rxTools#476]
Hello,

I have a O3DS with firmware 9.2.0-20E installed.

The problem, I can't install rxtools, with the browser, i tried each version of rxtools, with slot0x25KeyX and without, but there's everytime a black screen on launch,..

I tried to delete cookies of the launcher, reset the browser... I also tried to install rxtools via MenuHax but the same problem, Menuhax is stuck to the launch with a blackscreen when i start my 3ds.

What's the problem? What should I do?

Thanks by advance

**Comment by mariogamer2** [comment]
rxTools is no more maintained.

I suggst you to follow the guide: https://3ds.guide

**Comment by Reedkaan** [comment]
Hi, thank you for your answer.

I used this tutorial to hack my 3DS. So I have Decrypt9 , HB Launcher, Luma 3DS, hourglass and arm9loaderhax. 
But is it the same use that Rxtools?

Sorry for my questions, i'm new and there's a lot of things i don't understand yet.
