### ISSUE TITLE
N3DS Support

### ISSUE THREAD

**Issue by gudenau** [roxas75/rxTools#58]
I figured I would put this here, since it is planned and being worked on.

**Comment by mid-kid** [comment]
Update from the CakeHax department: Rei just merged N3DS MSET 4.x support, so you're covered there. (I'm unable to test it but Rei says it works...)

**Comment by AlbertoSONIC** [comment]
This is the first rxtools source able to boot emunand on the n3ds: https://github.com/AlbertoSONIC/rxTools-experimental
MyThread is still unstable (sometimes the Ver. String isn't patched) + it requires a fully unencrypted n3ds 9.5 firm named firm.dat in the root of the sdcard.

**Comment by 173210** [comment]
This issue should have been solved with commit 131b92ba5f4275fcb1226092c30e9ec6d8dc2c95. Please close.
