### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by 173210** [roxas75/rxTools#63]
README.md says "Support the original, not the imitation!" Licensing under a copyleft license allows to declare this more clearly.
If others made a modification of this tool, we can request the source code and include their changes.

**Comment by Syphurith** [comment]
If pleased it could be GPL since it's based on Decrypt9, which is stated as GPL.
Also, note that Decrypt9 has changed its sdmmc function implementations from Assembly to C.

**Comment by 173210** [comment]
Then it __should__ be licensed under GPL. That's copyleft. I suggest to obtain consensuses of maintainers.

**Comment by Syphurith** [comment]
If that could be changed to GPL, we may have sdmmc.s changed to sdmmc.c from decrypt9.
Hope that doesn't break anything. And, GPLv2/GPLv3, or simply follow decrypt9's?

**Comment by 173210** [comment]
Both of them are OK. But I suggest to use GPLv3.

**Comment by Syphurith** [comment]
I mean the `sdmmc.s`. That is disassembly fragment from Somwhere i don't know (maybe from GW?). So Normatt rewrote it to C implementation that wouldn't violate their own license anymore.

**Comment by 173210** [comment]
It's possible to include his implementation in GPLv2/v3.

**Comment by idgrepthat** [comment]
lol

**Comment by 173210** [comment]
Suggested to the PASTA team.

**Comment by dukesrg** [comment]
@roxas75, @AlbertoSONIC: Please consider this topic

**Comment by 173210** [comment]
PASTA team should be considering now. Let's wait for them.

**Comment by AlbertoSONIC** [comment]
Waiting for @motezazer and @capito27 ;)

**Comment by motezazer** [comment]
We are both OK with it.
GPLv2 was accepted by the whole team.

**Comment by 173210** [comment]
I'm just asking, but why not GPLv3?

**Comment by motezazer** [comment]
@173210 Because it requires to give any key needed to build the program, and the N3DS keys belong to Nintendo.

**Comment by 173210** [comment]
@motezazer Your software is not encrypted the key and, (in theory,) it's not necessary to run rxTools.
You know, even if en/decryptor software doesn't have key, it's completely OK, of course. Keys and Nintendo firmware are just data input to rxTools.

**Comment by motezazer** [comment]
@173210  New 3DS patches will need to be encrypted with the key. And we don't even know the scrambler algorithm. (So 3DS based encryption is needed)

**Comment by 173210** [comment]
@motezazer Well, patches themselves will need to be encrypted? 3DS based encryption doesn't matter because they are not statically linked (so rxTools doesn't modify them) .

**Comment by motezazer** [comment]
@173210 Patches themselves will need to be encrypted. I say "3DS based encryption" because the patches need to be encrypted by a 3DS before linking. (We don't know the scrambling algorithm.)

**Comment by 173210** [comment]
@motezazer Hmm, then actually it may be not compatible with GPLv3. Ok, I'll make a pull-request to change `LICENSE` and notice in files.

**Comment by Syphurith** [comment]
@173210 well once the license is picked, the issue may be solved. Eh so we would need to add GPL license mark before any new source files? *`.gitmodule` file does not really need it eh?*

**Comment by 173210** [comment]
Yes, we need add the notice. `.gitmodule` doesn't need it, but it has been added automatically. Anyway, it's not a problem.
