### ISSUE TITLE
Issues with using certain applets on 9.2 sysnand....

### ISSUE THREAD

**Issue by ApacheThunder** [roxas75/rxTools#71]
While booting into rxMode on sysnand friends list app crashes when attempting to use it and Notifications applet's menu freezes/doesn't update on bottom screen. (though you can still hear sound effects for the menu, so the applet isn't frozen. Just bottom screen not refreshing at all).

This seems the only effect 9.2 sysnand while in rxmode (emunand is uneffected if it's uptodate). If booted into devMode on sysnand, this issue is not present. I've heard from others this doesn't occur on 4.x. Seems to be a 9.x issue.

This issue has been present since initial release of 2.6 by Roxas75. (so it's not related to any changes you've done since then)

**Comment by lavanoid** [comment]
One issue that I've noticed is that when booted into emuNAND (latest version) and you put the system into sleep mode, it won't wake back up - the console is literally stuck in a coma x"D

**Comment by jaceyen** [comment]
The notification  crashed in emunand too(latest version)

**Comment by ApacheThunder** [comment]
I'm starting to see the Notifications applet not work properly on emunand and have the same issue as sysnand. (though friends list applet still works thus far) I would hope someone gets to fixing this issue sooner rather then later. :P

**Comment by lavanoid** [comment]
@ApacheThunder  Have you had this problem aswell? Weird glitch | 3DS: https://youtu.be/jJqkymfwJws

:/

**Comment by ApacheThunder** [comment]
It appears the latest build no longer has this issue. Both emunand and sysnand don't appear to show any anomalies in the applets. I'll close this issue for now as it appears to have been resolved.
