### ISSUE TITLE
Freeze after drawing the bottom screen image, only from MSET

### ISSUE THREAD

**Issue by AlbertoSONIC** [roxas75/rxTools#74]

**Comment by ApacheThunder** [comment]
I've never had this issue from MSET on 9.2. Perhaps effects only a specific firmware range?

**Comment by motezazer** [comment]
It's fixed with 7ebd4fabb3d0646e7e4e69f8feb49a5975a9f7ee

**Comment by ApacheThunder** [comment]
I see. Interesting. I never had freezes even before that commit. :P
