### ISSUE TITLE
No longer builds?

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#77]
Since cakehax was integrated, it doesn't build anymore.

Output:

C:\Users\Lavanoid\Documents\GitHub\rxTools>make
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxtools'

linking rxtools.elf
built ... rxtools.bin
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxtools'
0+1 records in
1+0 records out
917504 bytes (918 kB) copied, 0.005 seconds, 184 MB/s
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/CakeHax'

make[1]: *** No rul

**Comment by AlbertoSONIC** [comment]
You have to clone CakesHax repo inside rxtools folder ;)

**Comment by lavanoid** [comment]
Ah. Thank you!

**Comment by lavanoid** [comment]
Still got build issues:

C:\Users\Lavanoid\Documents\GitHub\rxTools>make
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxtools'

linking rxtools.elf
built ... rxtools.bin
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxtools'
0+1 records in
1+0 records out
917504 bytes (918 kB) copied, 0.004 seconds, 229 MB/s
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/rxmode'
make[1]: Entering directory `/c/Users/Lavanoid/Documents/GitHub/rxTools/CakeHax'

arm-none-eabi-as -mcpu=mpcore -mlittle-endian  -o build/mset_4x/arm11_tools.o so
urce/arm11_tools.s
make[1]: arm-none-eabi-as: Command not found
make[1]: *** [build/mset_4x/arm11_tools.o] Error 127
make[1]: Leaving directory `/c/
C:\Users\Lavanoid\Documents\GitHub\rxTools>

Here is my PATH variable:

PATH=C:\Program Files\ImageMagick-6.9.1-Q16;c:\devkitPro\msys\bin;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES (X86)\OVERLOOK FING 2.2\BIN;C:\PROGRAM FILES (X86)\OPENSSH\BIN;C:\MinGW\bin;C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\WINDOWS PERFORMANCE TOOLKIT\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\110\TOOLS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SDKS\TYPESCRIPT\1.0\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\120\TOOLS\BINN\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\PROGRAM FILES (X86)\OVERLOOK FING 2.2\BIN;C:\PROGRAM FILES (X86)\OPENSSH\BIN;C:\Users\Lavanoid\bin;C:\Python27;

**Comment by nastys** [comment]
[...]\devkitARM\bin is not in your PATH.

**Comment by lavanoid** [comment]
Neat. Thanks again :)
