### ISSUE TITLE
Adding some rainbows and unicorns - TWLN Decryption

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#81]
Could this be implemented?

https://gbatemp.net/threads/tutorial-installing-sudokuhax-on-3ds.388621/page-19#post-5567103

http://4dsdev.org/thread.php?pid=249#249

Would be really cool to inject Sudokuhax into my 9.2 sysNAND.

**Comment by ApacheThunder** [comment]
I second this. :D

**Comment by lavanoid** [comment]
Agreed
