### ISSUE TITLE
Remember what was selected on rxMenu

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#83]
Sorta frustrating when you're looking at say, the "Injector" options then when you press "B", it returns back to "rxMode" options. Would be more convenient if it remembered what was previously highlighted, instead of having to re-scroll though all the options, again.

**Comment by Syphurith** [comment]
That's really not hard to implement dude. I've ever tried that.
However the menu for "cool stuffs" (NAND File Dump/Inject) have a customized menu.
That menu prevents a smaller trace for menus and also a "Selected" menu backwards.

**Comment by lavanoid** [comment]
I see. Couldn't some sort of variable be set so when "Injection options" is selected, it gets given a value. Then when "B" is pressed, it goes back to the "Press A to access injection options" or whatever the variable is worth?

Just an idea. I have no experience in C, so. Would be pretty cool if it can be implemented :)

**Comment by Syphurith** [comment]
@lavanoid I mean for such a small enhancement, the menu inside "NAND File Dump/Inject" must be rewritten to suite the common and new design of menu. Indeed the menu itself could be done smarter.
`parentMenu` to record where user comes from.
`selectedItem` to record the index it was selected.
With these two variables, it could be implemented easily.
Unluckily i would be busy for at least a week. So sorry for that.

**Comment by lavanoid** [comment]
Okey doke :)

**Comment by AlbertoSONIC** [comment]
With my latest commit this issue has been fixed! :+1:

**Comment by lavanoid** [comment]
@AlbertoSONIC  I love you :3

Uploaded to my Nightly Dropbox :)

**Comment by AlbertoSONIC** [comment]
:D
