### ISSUE TITLE
Improvement: Unicode font support

### ISSUE THREAD

**Issue by dukesrg** [roxas75/rxTools#85]
It will be great to add a Unicode raster proportional font.
This will also allow the theme system redesign, as text will be a common resource with several languages support. Height of 12px will more readable and easier to optimize drawing with 3DS X/Y swapped screen.

**Comment by dukesrg** [comment]
Memo: http://sourceforge.net/projects/fontforgebuilds this tool can be used for font editing/converting in case we found a suitable font

**Comment by 5685C4A059D5** [comment]
Seconding. Seems very useful.

**Comment by dukesrg** [comment]
Used old version with DSTwo font, while can't open it now :(
Need to find free/opensource font with height=12px

**Comment by Syphurith** [comment]
@dukesrg There is `wqy` ([WenQuanYi](Wenq.org)) that known as the default font sets opensource for many linux distributions. If you need to generate the bitmaps, I suggest you to choose a Monospace one.

**Comment by dukesrg** [comment]
@Syphurith the goal is to use proportional as it looks more natural. With 3DS flipped X/Y framebuffer coordinates it is not a big deal to use proportional

**Comment by Syphurith** [comment]
@dukesrg Well. There are normal fonts it offers too. Or, there are opensourced fonts, on github.
Do you want to use TTF with the library, or just a bitmap one that might be faster?

**Comment by dukesrg** [comment]
Bitmap will be easier and faster

**Comment by Syphurith** [comment]
@dukesrg proportional? algorithem? I know there are some embeded solutions that uses bitmaps for different sizes, simply. Even 3DS itself may be just using different bitmaps without calculation with sizes.

**Comment by dukesrg** [comment]
Yes, proportional, in spite of monospace, means each symbol may have a different width in pexels, in case of bitmap, or in units in case of a vector on. Not much of use with Chinese characters but will be more readable with Latin

**Comment by Syphurith** [comment]
Oh you would meet small problems regarding Chinese or even just Japanese characters, or Korean.
Or you would like to seperate the drawing operations for CJK and Latin?

**Comment by dukesrg** [comment]
Which problem?

**Comment by Syphurith** [comment]
@dukesrg when you tried to get a smaller font bitmap from a bigger one..

**Comment by dukesrg** [comment]
@Syphurith you mean scaling the existing font to necessary size? I got what you meant, we will have a problem downscaling chineese/korean/japanese codepages, so we need 8 or better 12 pixel font

**Comment by dukesrg** [comment]
I think GNU Unifont will do the job, but it has 16 px in height

**Comment by 173210** [comment]
So you are concerning it can break the current UI?
By the way, I have used GNU Unifont for my first program for 3DS. It looks nice.
https://twitter.com/173210/status/465496520448430080

**Comment by dukesrg** [comment]
I think this version  c13bf321db9533459cb42b018bd52d35af7215fa from pool request #97 can be tested now.

**Comment by dukesrg** [comment]
Implemented in #97 along with other font/text related visual improvements

**Comment by dukesrg** [comment]
@Syphurith can you add/check chinese unicode support with the last commit?

**Comment by Syphurith** [comment]
@dukesrg Eh, sorry. Not convinient, for coding for days..
However if you need a Chinese version of the text (for the language support), you can give me what to translate and i would do in a day or two.

**Comment by dukesrg** [comment]
@Syphurith The new font have CJK unicode regions, so if you're able to build rxtools and edit lang.h with UTF-8 compatible text editor and add chinese version of strings - that is enough. Anyway this is pre-tet, I believe the language strings will extend greatly

**Comment by Syphurith** [comment]
@dukesrg now translated.. and getting it built. (fetching the imagemagick for windows)
Well there are chs (Chinese Simplified) and cht (Chinese Traditional).. Still haven't not tested it.
Once is that done should i just give translated text or make a pull?
`N_LANG` in `lib/lang.h` seems weird to me. There was text for 8 languages in the file (but it was 7).

**Comment by dukesrg** [comment]
@Syphurith I think if one works, the other will work too. As for the lenguage code Cht/Chs will be enought for now
just increase it by one for each language, looks it just counts from 0 :)

**Comment by Syphurith** [comment]
So if there is text for 9 languages, i would set it to 8?
And, do i need to create a text file first as its config so it choose chs directly?

**Comment by dukesrg** [comment]
@Syphurith looks like 8 will be right number.
For 3.0 you should use a new launcher URL in case you're using spiderhax to launch it because of the updated cakehax

**Comment by Syphurith** [comment]
Translated text below. I guess all text are from the `lib/lang.h`.

Variable | en_US| zh_cn
---- | ---- | ----
STR_LANGUAGES | L"Eng" | L"chs"
STR_FORCE_UI_BOOT | L"Force UI boot:         %ls" | L"强制UI启动：           %ls"
STR_SELECTED_THEME | L"Selected theme:     <%3c  >" | L"主题选用：           <%3c  >"
STR_SHOW_AGB | L"Show AGB_FIRM BIOS:    %ls" | L"显示AGB_FIRM BIOS：    %ls"
STR_ENABLE_3D_UI | L"Enable 3D UI:          %ls" | L"启用3D化UI：           %ls"
STR_QUICK_BOOT | L"Quick boot:            %ls" | L"快速启动：             %ls"
STR_CONSOLE_LANGUAGE | L"Language:           < %-4ls>" | L"语言选择：          < %-4ls>"
STR_AUTOBOOT | L"AUTOBOOT" | L"自动启动"
STR_HOLD_R | L"Hold R to go to the menu" | L"按着R键进入菜单"

This is given in case i can't get those tested and updated in time.

**Comment by Syphurith** [comment]
@dukesrg Eh.. My personal build of the 3.0 failed to start up with MSET 4.1 JPN.
Hope that's only my personal issue that rxTools.dat doesn't break (even cleaned the build first).

**Comment by dukesrg** [comment]
@Syphurith you tried with /cakes?rxTools.dat, right?

**Comment by capito27** [comment]
On one of the latest cake hax commit broke MSET launching as an option, you'll have to start RxTools though spider in the mean time

**Comment by capito27** [comment]
Well, nvm, cake hax was fixed; wasn't reading the right commit

**Comment by Syphurith** [comment]
@dukesrg Sorry no. I used the R4, not spider.

**Comment by dukesrg** [comment]
@Syphurith I got it. rxTools 2.6 was using GW-compatible payload. Since CakeHax was rewriten it also need updated MSET to be installed

**Comment by Syphurith** [comment]
@dukesrg Thanks for your effort on the pull. Even it could not run on my console yet, i'd better wait for a compatiable one. *Well i'm seen some troubles with #95 and i would try solve it.*

**Comment by dukesrg** [comment]
@Syphurith why didn't you use a spiderhax entry for now?

**Comment by Syphurith** [comment]
@dukesrg My network is awful. It is costly and not stable to do such. *<-false*
Eh also I don't like to set the HTTP server up every time i would need to access the emuNAND. *or say*
MSET is very easy for me to use, at least mine is still on 4.1. *<-true*

**Comment by dukesrg** [comment]
Started to implement JSON-based translations #105
Current goals:
- make it work with UTF-8 encoded locale files in /rxTools/lang/
- use f_readdir instead of predefined lang.json to get available translations
- move en.json and ASCII font.bin (eliminate font.h) into rxTools.dat with FilePack to make it able to work standalone and speed-up silent boot
Help and suggestions are welcome

**Comment by Syphurith** [comment]
@dukesrg @motezazer @AlbertoSONIC I thought this is solved now, since the 'unifont' is used.. Right?

**Comment by soarqin** [comment]
I think it is better to find a 12px unifont so that console can display more lines like before

**Comment by 173210** [comment]
@soarqin I guess it's difficult to read traditional Chinese characters of such small fonts.

**Comment by dukesrg** [comment]
I believe there is no raster font with height less then 16px with CN/KR/JP characters. The only thing to improve now is better glyph width handling, but anyway unifont is semi-monospace and all alphabetical character is treated as it should right now.

**Comment by soarqin** [comment]
Some windows ttc unicode fonts have 11-16px fonts embedded. I have converted some of them to raw fonts when wrote a book reader homebrew for psp. But unluckily I have lost source codes of the tool.

**Comment by 173210** [comment]
@dukesrg The PCF version of GNU Unifont should be useful.
@soarqin TTC is also an alternative for the current format, but Windows :-1:

**Comment by 173210** [comment]
By the way, here is a reference for PCF.
https://fontforge.github.io/en-US/documentation/reference/pcf-format/

**Comment by 173210** [comment]
Oh, I forgot to suggest to open another issue. Actually rxTools supports unicode font and this should be a different issue.

**Comment by soarqin** [comment]
@173210 ttc support needs freetype, it would greatly increase binary size. I meant converting ttc to raw pixel format

**Comment by 173210** [comment]
@dukesrg Aren't embedded ones bitmap?

**Comment by dukesrg** [comment]
@173210 you mean the current one rxtools uses? You should remember it is 1bpp and transposed. PCF is still a bitmap format so actually will have little to no difference with the unifont as a source.

**Comment by 173210** [comment]
@dukesrg Sorry, it was for @soarqin. Anyway, PCF can use different proportional fonts. It's not a limitation of bitmap fonts, but the one of the current implementation.

**Comment by dukesrg** [comment]
@173210 yes this can be useful and font file could be bound by themee if theme engine will be implemented. That could also some space by not including a font file in the distribution. But again, unifont is the most complete raster font for now and many things in the interface are using special pseudographics a characters now. So IMO theme engine must be revised first to get a full advantages from PCF font.

**Comment by dukesrg** [comment]
Some useful info was found here https://czyborra.com/unifont/
Good news, GNU intfonts have a number of 24px bitmap fonts http://directory.fsf.org/wiki/Intlfonts
Though I could not found a graphical glypth in there, it is really a minor problem, because only few of them was used in rxTools.

**Comment by Syphurith** [comment]
@dukesrg *Glad to see you again. Unicode is already been in use, but it causes some problems with text. The other thing i can tell about rxTools is currently it merely receives any updates for features..*

**Comment by dukesrg** [comment]
@Syphurith I'm about adding one more bigger font for menu headers, so themes won't contain any text and we can translate everything.

**Comment by 173210** [comment]
It's nice to add more options for theme, but it's not scalable. What if the theme want a larger or smaller fonts? It's not desirable to make the code more complex.

By the way, shouldn't it be another issue?

**Comment by dukesrg** [comment]
@173210 It's not about scaling at all. IMO noone will bother with vector fonts for rxTools in near future.
Just wanted to mention that we can easily add one more font size with only small code change. That will make potential language-independent themes look a bit nicer then just text with backround images beneath.
But you're right, I'd better open another issue about theme improvements, because it requires changing a lot of code, though it will make much easier to customize themes and even its contens, menu option order and etc. I wish I have time for that, but for now I can only try to gather codepages of Intlfonts into 24px bitmap font.

**Comment by dukesrg** [comment]
Continued in #394
