### ISSUE TITLE
MSET DG : 6.x instead of 5.x for Korean version

### ISSUE THREAD

**Issue by kot2002** [roxas75/rxTools#90]
Currently, rxTools' MSET DG for korean firms comes with 4.x and 5.x options.
However, to prevent soft-bricking issue of 2DS, 5.x should be changed to 6.x MSET.

0004001000027000 v2049 -> v3078

**Comment by Gadorach** [comment]
Which I would do, except there is no 6.x MSET available for the Korean 3DS models that I could find documentation for. Also, it's a placeholder, not meant to be used immediately, and has no ROP chain anyway. If you have the proper documentation, I'll be happy to add 6.x KOR to the MSET downgrade tool.

**Comment by Gadorach** [comment]
Pull request made, implemented properly, but not tested, as I have no access to a KOR console. Use at your own risk.

Details: 

KOR System Settings = 0004001000027000 v3078
Revision  = 0D
Hash = 560251840 = 2164C3C0

Enjoy.

**Comment by Gadorach** [comment]
@kot2002 could you send me your msetdg.bin files for the KOR region, if you still have them? They're not on NUS anymore, so I can't as easily back them up. If you have CIAs of the same files, that would be fine as well, I can generate the needed files from the CIAs.
