### ISSUE TITLE
Possibly a better configuration file?

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#92]
Would it be possible to implement a better configuration file layout?

Maybe have it something like this:

auto_boot=0 // No
theme=1 // Theme 1
show_agb_bios=1 // yes
emunand_ver_label=RX3D // I personally changed this to "Ver."

etc.

Just wondering as rxTools is pretty much the best 3DS util/CFW that's available, why not make it more versatile and flexible? :3

**Comment by dukesrg** [comment]
Fork it, add it, push it, merge it! :)

**Comment by lavanoid** [comment]
I wish I knew how ;_;

**Comment by Syphurith** [comment]
@lavanoid It is not so difficult if take `#` as comment mark. Here comes the fragment for config file!
```
#Autoboot? 0 - default (it does auto boot), 1 - custom (everytime you have to choose)
autoboot=0
```
When fetching the options:
1.Find `\n`: This is **line end**, get all those chars in the buffer to interprete. Also this resets states.
2.FInd `#`: Now we don't need characters, till the line end. No chars get into buffer.
3.Find `=`: Get the characters present into the `option name`. Also omit this char, clear buffer.
When interprete:
1.Empty: Nothing to do.
2.when `option name` is valid, try to convert the value from buffer (those after `=`) and set it.
State for buffer reading:
1.Comment began, set when meets `#`. if set, all except line end get omitted.
2.Options mark, set when sees `=`. If set, content (option name as name, buffer as value) be dealt.
Eh not so difficult, yup.

**Comment by lavanoid** [comment]
I wish I was as awesome as you guys. I literally have no idea how to write in C/C++. I just provide ideas, bug reports and a few batch file modifications and stuff like that :P

**Comment by 173210** [comment]
Shall I implement JSON parser? Such a change which can break compatibility should be done as soon as possible.

**Comment by lavanoid** [comment]
Sounds neat. Wonder what the Pasta team say about it...

**Comment by AlbertoSONIC** [comment]
Definitely a good idea.  :)

**Comment by dukesrg** [comment]
:+1: it can be used for language files too!

**Comment by 173210** [comment]
One of the advantage is that we don't have to reinvent the wheel.

I found a nice, super-lightweight parser. I'll port this to rxTools...
https://github.com/udp/json-parser

**Comment by lavanoid** [comment]
Nice :) Seems that the majority  are up for it. Go ahead :D

**Comment by 173210** [comment]
json-parser needs malloc, so I decided to port [jsmn](https://bitbucket.org/zserge/jsmn/), which doesn't need it.

**Comment by 173210** [comment]
JSON writer works fine. I'm working on parser now...

**Comment by dukesrg** [comment]
@173210 great! What's the issue with malloc?

**Comment by 173210** [comment]
rxTools just doesn't have malloc.

**Comment by dukesrg** [comment]
@173210 man, that's why I failed to convert char to wchar_t using malloc :)))

**Comment by 173210** [comment]
@dukesrg Did you solve the problem?

**Comment by dukesrg** [comment]
@173210 Nore or less. The only one left is how to load 2Mb font file into memory with no malloc :)

**Comment by 173210** [comment]
LOL

**Comment by 173210** [comment]
Ok, now it works. jsmn doesn't need any modification.

**Comment by Syphurith** [comment]
@dukesrg I don't know if the 2MB wouldn't cause more problems.. (Hope it does not)
Always there are much less characters used than given in font file. building a cache file and load that (with mapping.) in memory might be good, but i don't know if that could cause much problems.

**Comment by dukesrg** [comment]
@Syphurith problem solved, takes only additional portion of a second displaying "Loading..." before plashscreen to load 2Mb font. Now waiting for the JSON support

**Comment by 173210** [comment]
@nastys You can close this issue.

**Comment by lavanoid** [comment]
Done :)
