### ISSUE TITLE
Start and Select buttons are oddly mapped

### ISSUE THREAD

**Issue by lavanoid** [roxas75/rxTools#93]
It's sorta weird that Start = Shutdown and Select = Reboot while on other utilities, its the opposite way round. I think it should be more "unified", meaning that Start = Reboot (Like Ninjhax and D9) and Select = Shutdown.

The current themes don't explain the buttons operations either. Maybe display it on the top screen?

So yeah, 2 things:

1.) Switch start and select buttons around.
2.) Maybe update the top screen of themes to reflect the operation of the keys.

:)

**Comment by AlbertoSONIC** [comment]
Yeah I thought the same thing yesterday, when I turned off the 3ds instead of rebooting, by pressing the Start button... Surely a thing to change ;)

**Comment by lavanoid** [comment]
I think I just managed to do it... Made a pull request.

**Comment by Syphurith** [comment]
if this is already solved, you may close this issue if you find it flawless as your expectation.

**Comment by lavanoid** [comment]
Will do :)
